<template><div><h1 id="box3" tabindex="-1"><a class="header-anchor" href="#box3" aria-hidden="true">#</a> Box3</h1>
<p>表示三维空间中的一个轴对齐包围盒（axis-aligned bounding box，AABB）。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> box <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Box3</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token keyword">const</span> mesh <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Mesh</span><span class="token punctuation">(</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>SphereGeometry</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>MeshBasicMaterial</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// ensure the bounding box is computed for its geometry // this should be done only once (assuming static geometries) mesh.geometry.computeBoundingBox(); // ... // in the animation loop, compute the current bounding box with the world matrix box.copy( mesh.geometry.boundingBox ).applyMatrix4( mesh.matrixWorld );</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="构造器-constructor" tabindex="-1"><a class="header-anchor" href="#构造器-constructor" aria-hidden="true">#</a> 构造器（Constructor）</h2>
<h3 id="box3-min-vector3-max-vector3" tabindex="-1"><a class="header-anchor" href="#box3-min-vector3-max-vector3" aria-hidden="true">#</a> Box3( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> )</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - (参数可选) <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示包围盒的下边界。 默认值是（ + Infinity, + Infinity, + Infinity ）。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - (参数可选) <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示包围盒的上边界。 默认值是（ - Infinity, - Infinity, - Infinity ）。</p>
<p>创建一个以max和min为边界的包围盒。</p>
<h2 id="属性-properties" tabindex="-1"><a class="header-anchor" href="#属性-properties" aria-hidden="true">#</a> 属性（Properties）</h2>
<h3 id="isbox3-boolean" tabindex="-1"><a class="header-anchor" href="#isbox3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.isBox3" target="_blank" rel="noopener noreferrer">isBox3<ExternalLinkIcon/></a> : Boolean</h3>
<p>Read-only flag to check if a given object is of type Box3.</p>
<h3 id="min-vector3" tabindex="-1"><a class="header-anchor" href="#min-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示包围盒的下边界。
默认值是（ + Infinity, + Infinity, + Infinity ）。</p>
<h3 id="max-vector3" tabindex="-1"><a class="header-anchor" href="#max-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 包围盒的(x, y, z)上边界。
默认值是 ( - Infinity, - Infinity, - Infinity ).</p>
<h2 id="方法-methods" tabindex="-1"><a class="header-anchor" href="#方法-methods" aria-hidden="true">#</a> 方法（Methods）</h2>
<h3 id="applymatrix4-matrix-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-matrix-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( matrix : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a> - 要应用的 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a></p>
<p>使用传入的矩阵变换Box3（包围盒8个顶点都会乘以这个变换矩阵）。</p>
<h3 id="clamppoint-point-vector3-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#clamppoint-point-vector3-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.clampPoint" target="_blank" rel="noopener noreferrer">clampPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 需要做clamp 的坐标 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会被拷贝到这个对象中</p>
<p>使这个点<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> <a href="https://en.wikipedia.org/wiki/Clamping_(graphics)" target="_blank" rel="noopener noreferrer">Clamps<ExternalLinkIcon/></a>(处于范围内) 处于包围盒边界范围内。</p>
<h3 id="clone-box3" tabindex="-1"><a class="header-anchor" href="#clone-box3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a></h3>
<p>返回一个与该包围盒子有相同下边界<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> 和上边界 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a>的新包围盒。</p>
<h3 id="containsbox-box-box3-boolean" tabindex="-1"><a class="header-anchor" href="#containsbox-box-box3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.containsBox" target="_blank" rel="noopener noreferrer">containsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 需要检测是否在当前包围盒内的 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>。</p>
<p>传入的 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 整体都被包含在该对象中则返回true。如果他们两个包围盒是一样的也返回true。</p>
<h3 id="containspoint-point-vector3-boolean" tabindex="-1"><a class="header-anchor" href="#containspoint-point-vector3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.containsPoint" target="_blank" rel="noopener noreferrer">containsPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 需要检测是否在当前包围盒内的 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>当传入的值 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> 在包围盒内部或者边界都会返回true。</p>
<h3 id="copy-box-box3-this" tabindex="-1"><a class="header-anchor" href="#copy-box-box3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 需要复制的包围盒 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> 。</p>
<p>将传入的值 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 中的 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> 拷贝到当前对象。</p>
<h3 id="distancetopoint-point-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancetopoint-point-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.distanceToPoint" target="_blank" rel="noopener noreferrer">distanceToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 用来测试距离的点 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>返回这个box的任何边缘到指定点的距离。如果这个点位于这个盒子里，距离将是0。</p>
<h3 id="equals-box-box3-boolean" tabindex="-1"><a class="header-anchor" href="#equals-box-box3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将box与当前对象做比较。</p>
<p>返回true如果传入的值与当前的对象 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 有相同的上下边界。</p>
<h3 id="expandbyobject-object-object3d-this" tabindex="-1"><a class="header-anchor" href="#expandbyobject-object-object3d-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.expandByObject" target="_blank" rel="noopener noreferrer">expandByObject<ExternalLinkIcon/></a> ( object : <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">object<ExternalLinkIcon/></a> - 包裹在包围盒中的3d对象 <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a>。</p>
<p>扩展此包围盒的边界，使得对象及其子对象在包围盒内，包括对象和子对象的世界坐标的变换。 该方法可能会导致一个比严格需要的更大的框。</p>
<h3 id="expandbypoint-point-vector3-this" tabindex="-1"><a class="header-anchor" href="#expandbypoint-point-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.expandByPoint" target="_blank" rel="noopener noreferrer">expandByPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 需要在包围盒中的点 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>扩展这个包围盒的边界使得该点（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>）在包围盒内。</p>
<h3 id="expandbyscalar-scalar-float-this" tabindex="-1"><a class="header-anchor" href="#expandbyscalar-scalar-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.expandByScalar" target="_blank" rel="noopener noreferrer">expandByScalar<ExternalLinkIcon/></a> ( scalar : Float ) : this</h3>
<p>scalar - 扩展包围盒的比例。</p>
<p>按 scalar 的值展开盒子的每个维度。如果是负数，盒子的尺寸会缩小。</p>
<h3 id="expandbyvector-vector-vector3-this" tabindex="-1"><a class="header-anchor" href="#expandbyvector-vector-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.expandByVector" target="_blank" rel="noopener noreferrer">expandByVector<ExternalLinkIcon/></a> ( vector : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> - 扩展包围盒的数值 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 。</p>
<p>按 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> 每个纬度的值展开这个箱子。 这个盒子的宽度将由 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> 的x分量在两个方向上展开。 这个盒子的高度将由 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> 两个方向上的y分量展开。 这个盒子的深度将由 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> z分量在两个方向上展开。</p>
<h3 id="getboundingsphere-target-sphere-sphere" tabindex="-1"><a class="header-anchor" href="#getboundingsphere-target-sphere-sphere" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.getBoundingSphere" target="_blank" rel="noopener noreferrer">getBoundingSphere<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 如果指定了target ，结果将会被拷贝到target。</p>
<p>获取一个包围球 <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>。</p>
<h3 id="getcenter-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#getcenter-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.getCenter" target="_blank" rel="noopener noreferrer">getCenter<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 如果指定了target ，结果将会被拷贝到target。</p>
<p>返回包围盒的中心点 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<h3 id="getparameter-point-vector3-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#getparameter-point-vector3-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.getParameter" target="_blank" rel="noopener noreferrer">getParameter<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>.
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 如果指定了target ，结果将会被拷贝到target。</p>
<p>返回一个点为这个盒子的宽度、高度和深度的比例。</p>
<h3 id="getsize-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#getsize-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.getSize" target="_blank" rel="noopener noreferrer">getSize<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 如果指定了target ，结果将会被拷贝到target。</p>
<p>返回包围盒的宽度，高度，和深度。</p>
<h3 id="intersect-box-box3-this" tabindex="-1"><a class="header-anchor" href="#intersect-box-box3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.intersect" target="_blank" rel="noopener noreferrer">intersect<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 与包围盒的交集</p>
<p>计算此包围盒和 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 的交集，将此框的上界设置为两个框的max的较小部分， 将此包围盒的下界设置为两个包围盒的min的较大部分。如果两个包围盒不相交，则清空此包围盒。</p>
<h3 id="intersectsbox-box-box3-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsbox-box-box3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.intersectsBox" target="_blank" rel="noopener noreferrer">intersectsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 用来检测是否相交的包围盒</p>
<p>确定当前包围盒是否与传入包围盒<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 相交。</p>
<h3 id="intersectsplane-plane-plane-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsplane-plane-plane-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.intersectsPlane" target="_blank" rel="noopener noreferrer">intersectsPlane<ExternalLinkIcon/></a> ( plane : <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> - 用来检测是否相交的 <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>。</p>
<p>确定当前包围盒是否与平面 <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> 相交。</p>
<h3 id="intersectssphere-sphere-sphere-boolean" tabindex="-1"><a class="header-anchor" href="#intersectssphere-sphere-sphere-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.intersectsSphere" target="_blank" rel="noopener noreferrer">intersectsSphere<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> - 用来检测是否相交的球体 <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>。</p>
<p>确定当前包围盒是否与球体 <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> 相交。</p>
<h3 id="intersectstriangle-triangle-triangle-boolean" tabindex="-1"><a class="header-anchor" href="#intersectstriangle-triangle-triangle-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.intersectsTriangle" target="_blank" rel="noopener noreferrer">intersectsTriangle<ExternalLinkIcon/></a> ( triangle : <a href="https://threejs.org/docs/index.html#api/zh/math/Triangle" target="_blank" rel="noopener noreferrer">Triangle<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Triangle" target="_blank" rel="noopener noreferrer">triangle<ExternalLinkIcon/></a> - 用来检测是否相交的三角形 <a href="https://threejs.org/docs/index.html#api/zh/math/Triangle" target="_blank" rel="noopener noreferrer">Triangle<ExternalLinkIcon/></a>。</p>
<p>确定当前包围盒是否与三角形 <a href="https://threejs.org/docs/index.html#api/zh/math/Triangle" target="_blank" rel="noopener noreferrer">triangle<ExternalLinkIcon/></a> 相交。</p>
<h3 id="isempty-boolean" tabindex="-1"><a class="header-anchor" href="#isempty-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.isEmpty" target="_blank" rel="noopener noreferrer">isEmpty<ExternalLinkIcon/></a> () : Boolean</h3>
<p>如果这个盒子包含0个顶点，则返回true。
注意，下界和上界相等的方框仍然包含一个点，即两个边界共享的那个点。</p>
<h3 id="makeempty-this" tabindex="-1"><a class="header-anchor" href="#makeempty-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.makeEmpty" target="_blank" rel="noopener noreferrer">makeEmpty<ExternalLinkIcon/></a> () : this</h3>
<p>清空包围盒。</p>
<h3 id="set-min-vector3-max-vector3-this" tabindex="-1"><a class="header-anchor" href="#set-min-vector3-max-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示下边界每个纬度（x,y,z）的值。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示上边界每个纬度（x,y,z）的值。</p>
<p>设置包围盒上下边界每个纬度（x,y,z)的值。
请注意，此方法仅复制给定对象的值。</p>
<h3 id="setfromarray-array-array-this" tabindex="-1"><a class="header-anchor" href="#setfromarray-array-array-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.setFromArray" target="_blank" rel="noopener noreferrer">setFromArray<ExternalLinkIcon/></a> ( array : Array ) : this</h3>
<p>array - 数组当中的所有的点都将被包围盒包裹。</p>
<p>设置包围盒的上下边界使得数组 <strong>array</strong> 中的所有点的点都被包含在内。</p>
<h3 id="setfrombufferattribute-attribute-bufferattribute-this" tabindex="-1"><a class="header-anchor" href="#setfrombufferattribute-attribute-bufferattribute-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.setFromBufferAttribute" target="_blank" rel="noopener noreferrer">setFromBufferAttribute<ExternalLinkIcon/></a> ( attribute : <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">BufferAttribute<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> - 位置的缓冲数据，包含在返回的包围盒内。</p>
<p>设置此包围盒的上边界和下边界，以包含 <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> 中的所有位置数据。</p>
<h3 id="setfromcenterandsize-center-vector3-size-vector3-this" tabindex="-1"><a class="header-anchor" href="#setfromcenterandsize-center-vector3-size-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.setFromCenterAndSize" target="_blank" rel="noopener noreferrer">setFromCenterAndSize<ExternalLinkIcon/></a> ( center : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, size : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>, - 包围盒所要设置的中心位置。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">size<ExternalLinkIcon/></a> - 包围盒所要设置的x、y和z尺寸（宽/高/长）。</p>
<p>将当前包围盒的中心点设置为 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> ，并将此包围盒的宽度，高度和深度设置为大小指定 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">size<ExternalLinkIcon/></a> 的值。</p>
<h3 id="setfromobject-object-object3d-this" tabindex="-1"><a class="header-anchor" href="#setfromobject-object-object3d-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.setFromObject" target="_blank" rel="noopener noreferrer">setFromObject<ExternalLinkIcon/></a> ( object : <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">object<ExternalLinkIcon/></a> - 用来计算包围盒的3D对象 <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a>。</p>
<p>计算和世界轴对齐的一个对象 <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a> （含其子对象）的包围盒，计算对象和子对象的世界坐标变换。 该方法可能会导致一个比严格需要的更大的框。</p>
<h3 id="setfrompoints-points-array-this" tabindex="-1"><a class="header-anchor" href="#setfrompoints-points-array-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.setFromPoints" target="_blank" rel="noopener noreferrer">setFromPoints<ExternalLinkIcon/></a> ( points : Array ) : this</h3>
<p>points - 计算出的包围盒将包含数组中所有的点 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3s<ExternalLinkIcon/></a></p>
<p>设置此包围盒的上边界和下边界，以包含数组 points 中的所有点。</p>
<h3 id="translate-offset-vector3-this" tabindex="-1"><a class="header-anchor" href="#translate-offset-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.translate" target="_blank" rel="noopener noreferrer">translate<ExternalLinkIcon/></a> ( offset : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a> - 偏移方向和距离。</p>
<p>给包围盒的上下边界添加偏移量 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a>，这样可以有效的在3D空间中移动包围盒。 偏移量为 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a> 大小。</p>
<h3 id="union-box-box3-this" tabindex="-1"><a class="header-anchor" href="#union-box-box3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box3.union" target="_blank" rel="noopener noreferrer">union<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将被用于与该盒子计算并集的盒子。</p>
<p>在 <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> 参数的上边界和已有box对象的上边界之间取较大者，而对两者的下边界取较小者，这样获得一个新的较大的联合盒子。</p>
</div></template>


