<template><div><h1 id="三维几何线段-line3" tabindex="-1"><a class="header-anchor" href="#三维几何线段-line3" aria-hidden="true">#</a> 三维几何线段（Line3）</h1>
<p>用起点和终点表示的几何线段。</p>
<h2 id="构造器-constructor" tabindex="-1"><a class="header-anchor" href="#构造器-constructor" aria-hidden="true">#</a> 构造器（Constructor）</h2>
<h3 id="line3-start-vector3-end-vector3" tabindex="-1"><a class="header-anchor" href="#line3-start-vector3-end-vector3" aria-hidden="true">#</a> Line3( start : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, end : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> )</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> - 线段的起始点。默认值为 (0, 0, 0)。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> - 线段的终点。默认值为 (0, 0, 0)。</p>
<p>创建一个三维几何线段 Line3。</p>
<h2 id="属性-properties" tabindex="-1"><a class="header-anchor" href="#属性-properties" aria-hidden="true">#</a> 属性（Properties）</h2>
<h3 id="start-vector3" tabindex="-1"><a class="header-anchor" href="#start-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示线段的起点。</p>
<h3 id="end-vector3" tabindex="-1"><a class="header-anchor" href="#end-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 表示线段的终点</p>
<h2 id="方法-methods" tabindex="-1"><a class="header-anchor" href="#方法-methods" aria-hidden="true">#</a> 方法（Methods）</h2>
<h3 id="applymatrix4-matrix-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-matrix-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( matrix : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>对此线段应用矩阵变换。</p>
<h3 id="at-t-float-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#at-t-float-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.at" target="_blank" rel="noopener noreferrer">at<ExternalLinkIcon/></a> ( t : Float, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p>t - 使用值0-1返回沿线段的位置。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 计算结果会被拷贝到target。</p>
<p>返回一个线段某一位置的向量，当 t = 0的时候返回起始点，当t = 1的时候返回终点。</p>
<h3 id="clone-line3" tabindex="-1"><a class="header-anchor" href="#clone-line3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Line3" target="_blank" rel="noopener noreferrer">Line3<ExternalLinkIcon/></a></h3>
<p>返回一个与此线段拥有相同起始点 <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> 和 终点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> 的线段。</p>
<h3 id="closestpointtopoint-point-vector3-clamptoline-boolean-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#closestpointtopoint-point-vector3-clamptoline-boolean-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.closestPointToPoint" target="_blank" rel="noopener noreferrer">closestPointToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, clampToLine : Boolean, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 用于计算线段上到该点最近的点。
clampToLine - 是否将结果限制在线段起始点和终点之间。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果会拷贝到target。</p>
<p>返回线段上到point最近的点。如果参数 clampToLine 为true。返回值将会在线段之间。</p>
<h3 id="closestpointtopointparameter-point-vector3-clamptoline-boolean-float" tabindex="-1"><a class="header-anchor" href="#closestpointtopointparameter-point-vector3-clamptoline-boolean-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.closestPointToPointParameter" target="_blank" rel="noopener noreferrer">closestPointToPointParameter<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, clampToLine : Boolean ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 用于计算返回值的点
clampToLine - 结果是否处于 [0, 1]之间。</p>
<p>返回一个基于点投影到线段上的点的参数。如果 clampToLine 为true则返回值将在0到1之间。</p>
<h3 id="copy-line-line3-this" tabindex="-1"><a class="header-anchor" href="#copy-line-line3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( line : <a href="https://threejs.org/docs/index.html#api/zh/math/Line3" target="_blank" rel="noopener noreferrer">Line3<ExternalLinkIcon/></a> ) : this</h3>
<p>拷贝传入线段的起始点 <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> 和终点 <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> 向量到当前线段。</p>
<h3 id="delta-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#delta-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.delta" target="_blank" rel="noopener noreferrer">delta<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会拷贝到target。</p>
<p>返回线段的向量。（终点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a>向量减去起始点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a>向量）。</p>
<h3 id="distance-float" tabindex="-1"><a class="header-anchor" href="#distance-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.distance" target="_blank" rel="noopener noreferrer">distance<ExternalLinkIcon/></a> () : Float</h3>
<p>Returns the <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a> (straight-line distance) between the line's <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> and <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> points.</p>
<h3 id="distancesq-float" tabindex="-1"><a class="header-anchor" href="#distancesq-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.distanceSq" target="_blank" rel="noopener noreferrer">distanceSq<ExternalLinkIcon/></a> () : Float</h3>
<p>返回起始点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a>和终点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a>的欧几里得距离<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a>。（直线距离）</p>
<h3 id="equals-line-line3-boolean" tabindex="-1"><a class="header-anchor" href="#equals-line-line3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( line : <a href="https://threejs.org/docs/index.html#api/zh/math/Line3" target="_blank" rel="noopener noreferrer">Line3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Line3" target="_blank" rel="noopener noreferrer">line<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Line3" target="_blank" rel="noopener noreferrer">Line3<ExternalLinkIcon/></a> to compare with this one.</p>
<p>如果给定线段与当前线段的起始点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a>和终点<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a>都相同则返回true。</p>
<h3 id="getcenter-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#getcenter-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.getCenter" target="_blank" rel="noopener noreferrer">getCenter<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果会写入target。</p>
<p>返回线段的中心点。</p>
<h3 id="set-start-vector3-end-vector3-this" tabindex="-1"><a class="header-anchor" href="#set-start-vector3-end-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Line3.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( start : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, end : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">start<ExternalLinkIcon/></a> - 设置线段的起点 <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.start" target="_blank" rel="noopener noreferrer">start point<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">end<ExternalLinkIcon/></a> - 设置线段的终点 <a href="https://threejs.org/docs/index.html#api/zh/math/Line3.end" target="_blank" rel="noopener noreferrer">end point<ExternalLinkIcon/></a>。</p>
<p>将传入的向量设置到线段的起始点和终点。</p>
</div></template>


