<template><div><h1 id="四维矩阵-matrix4" tabindex="-1"><a class="header-anchor" href="#四维矩阵-matrix4" aria-hidden="true">#</a> 四维矩阵（Matrix4）</h1>
<p>表示为一个 4x4 <a href="https://en.wikipedia.org/wiki/Matrix_(mathematics)" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a>.</p>
<p>在3D计算机图形学中，4x4矩阵最常用的用法是作为一个变换矩阵<a href="https://en.wikipedia.org/wiki/Transformation_matrix" target="_blank" rel="noopener noreferrer">Transformation Matrix<ExternalLinkIcon/></a>。 有关WebGL中使用的变换矩阵的介绍，请参阅本教程<a href="http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices" target="_blank" rel="noopener noreferrer">this tutorial<ExternalLinkIcon/></a>。</p>
<p>这使得表示三维空间中的一个点的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>通过乘以矩阵来进行转换，如平移、旋转、剪切、缩放、反射、正交或透视投影等。这就是把矩阵<em>应用</em>到向量上。</p>
<p>任何3D物体<a href="https://threejs.org/docs/index.html#api/zh/core/Object3D" target="_blank" rel="noopener noreferrer">Object3D<ExternalLinkIcon/></a>都有三个关联的矩阵：</p>
<ul>
<li><a href="https://threejs.org/docs/index.html#api/zh/core/Object3D.matrix" target="_blank" rel="noopener noreferrer">Object3D.matrix<ExternalLinkIcon/></a>: 存储物体的本地变换矩阵。 这是对象相对于其父对象的变换矩阵。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/core/Object3D.matrixWorld" target="_blank" rel="noopener noreferrer">Object3D.matrixWorld<ExternalLinkIcon/></a>: 对象的全局或世界变换矩阵。如果对象没有父对象，那么这与存储在矩阵<a href="https://threejs.org/docs/index.html#api/zh/core/Object3D.matrix" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a>中的本地变换矩阵相同。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/core/Object3D.modelViewMatrix" target="_blank" rel="noopener noreferrer">Object3D.modelViewMatrix<ExternalLinkIcon/></a>: 表示对象相对于摄像机坐标系的变换矩阵， 一个对象的 modelViewMatrix 是物体世界变换矩阵乘以摄像机相对于世界空间变换矩阵的逆矩阵。</li>
</ul>
<p>摄像机<a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera" target="_blank" rel="noopener noreferrer">Cameras<ExternalLinkIcon/></a> 有三个额外的四维矩阵:</p>
<ul>
<li><a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera.matrixWorldInverse" target="_blank" rel="noopener noreferrer">Camera.matrixWorldInverse<ExternalLinkIcon/></a>: 视矩阵 - 摄像机世界坐标变换的逆矩阵。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera.projectionMatrix" target="_blank" rel="noopener noreferrer">Camera.projectionMatrix<ExternalLinkIcon/></a>: 投影变换矩阵，表示将场景中的信息投影到裁剪空间。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera.projectionMatrixInverse" target="_blank" rel="noopener noreferrer">Camera.projectionMatrixInverse<ExternalLinkIcon/></a>: 投影变换矩阵的逆矩阵。</li>
</ul>
<p>注意：物体的正规矩阵 <a href="https://threejs.org/docs/index.html#api/zh/core/Object3D.normalMatrix" target="_blank" rel="noopener noreferrer">Object3D.normalMatrix<ExternalLinkIcon/></a> 并不是一个4维矩阵，而是一个三维矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a>。</p>
<h2 id="注意行优先列优先的顺序。" tabindex="-1"><a class="header-anchor" href="#注意行优先列优先的顺序。" aria-hidden="true">#</a> 注意行优先列优先的顺序。</h2>
<p>设置set()方法参数采用行优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">row-major<ExternalLinkIcon/></a>， 而它们在内部是用列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>顺序存储在数组当中。</p>
<p>这意味着</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> m <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Matrix4</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

m<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span> <span class="token number">11</span><span class="token punctuation">,</span> <span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token punctuation">,</span> <span class="token number">14</span><span class="token punctuation">,</span>
       <span class="token number">21</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">23</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span>
       <span class="token number">31</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">33</span><span class="token punctuation">,</span> <span class="token number">34</span><span class="token punctuation">,</span>
       <span class="token number">41</span><span class="token punctuation">,</span> <span class="token number">42</span><span class="token punctuation">,</span> <span class="token number">43</span><span class="token punctuation">,</span> <span class="token number">44</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>元素数组<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a>将存储为:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>m<span class="token punctuation">.</span>elements <span class="token operator">=</span> <span class="token punctuation">[</span> <span class="token number">11</span><span class="token punctuation">,</span> <span class="token number">21</span><span class="token punctuation">,</span> <span class="token number">31</span><span class="token punctuation">,</span> <span class="token number">41</span><span class="token punctuation">,</span>
               <span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">42</span><span class="token punctuation">,</span>
               <span class="token number">13</span><span class="token punctuation">,</span> <span class="token number">23</span><span class="token punctuation">,</span> <span class="token number">33</span><span class="token punctuation">,</span> <span class="token number">43</span><span class="token punctuation">,</span>
               <span class="token number">14</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token number">44</span> <span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在内部，所有的计算都是使用列优先顺序进行的。然而，由于实际的排序在数学上没有什么不同， 而且大多数人习惯于以行优先顺序考虑矩阵，所以three.js文档以行为主的顺序显示矩阵。 请记住，如果您正在阅读源代码，您必须对这里列出的任何矩阵进行转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">transpose<ExternalLinkIcon/></a>，以理解计算。</p>
<h2 id="提取位置-平移-、旋转和缩放" tabindex="-1"><a class="header-anchor" href="#提取位置-平移-、旋转和缩放" aria-hidden="true">#</a> 提取位置(平移)、旋转和缩放</h2>
<p>有多种选项可用于从 Matrix4 中提取位置、旋转和缩放。</p>
<ul>
<li><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrixPosition" target="_blank" rel="noopener noreferrer">Vector3.setFromMatrixPosition<ExternalLinkIcon/></a>：可用于提取位置相关的分量。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrixScale" target="_blank" rel="noopener noreferrer">Vector3.setFromMatrixScale<ExternalLinkIcon/></a>：可用于提取缩放相关的分量。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.setFromRotationMatrix" target="_blank" rel="noopener noreferrer">Quaternion.setFromRotationMatrix<ExternalLinkIcon/></a>, <a href="https://threejs.org/docs/index.html#api/zh/math/Euler.setFromRotationMatrix" target="_blank" rel="noopener noreferrer">Euler.setFromRotationMatrix<ExternalLinkIcon/></a> 或 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.extractRotation" target="_blank" rel="noopener noreferrer">extractRotation<ExternalLinkIcon/></a>：可用于从纯(未缩放)矩阵中提取旋转相关分量。</li>
<li><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.decompose" target="_blank" rel="noopener noreferrer">decompose<ExternalLinkIcon/></a>：可用于一次性提取位置、旋转和缩放</li>
</ul>
<h2 id="构造器-constructor" tabindex="-1"><a class="header-anchor" href="#构造器-constructor" aria-hidden="true">#</a> 构造器（Constructor）</h2>
<h3 id="matrix4" tabindex="-1"><a class="header-anchor" href="#matrix4" aria-hidden="true">#</a> Matrix4()</h3>
<p>创建并初始化一个4X4的单位矩阵<a href="https://en.wikipedia.org/wiki/Identity_matrix" target="_blank" rel="noopener noreferrer">identity matrix<ExternalLinkIcon/></a>.</p>
<h2 id="属性-properties" tabindex="-1"><a class="header-anchor" href="#属性-properties" aria-hidden="true">#</a> 属性（Properties）</h2>
<h3 id="elements-array" tabindex="-1"><a class="header-anchor" href="#elements-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a> : Array</h3>
<p>矩阵列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>列表。</p>
<h2 id="方法-methods" tabindex="-1"><a class="header-anchor" href="#方法-methods" aria-hidden="true">#</a> 方法（Methods）</h2>
<h3 id="clone-matrix4" tabindex="-1"><a class="header-anchor" href="#clone-matrix4" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a></h3>
<p>创建一个新的矩阵，元素<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a>与该矩阵相同。</p>
<h3 id="compose-position-vector3-quaternion-quaternion-scale-vector3-this" tabindex="-1"><a class="header-anchor" href="#compose-position-vector3-quaternion-quaternion-scale-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.compose" target="_blank" rel="noopener noreferrer">compose<ExternalLinkIcon/></a> ( position : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, quaternion : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, scale : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>设置将该对象位置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">position<ExternalLinkIcon/></a>，四元数<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">quaternion<ExternalLinkIcon/></a> 和 缩放<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">scale<ExternalLinkIcon/></a> 组合变换的矩阵。</p>
<h3 id="copy-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#copy-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的元素<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a>复制到当前矩阵中。</p>
<h3 id="copyposition-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#copyposition-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.copyPosition" target="_blank" rel="noopener noreferrer">copyPosition<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将给定矩阵 m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> 的平移分量拷贝到当前矩阵中。</p>
<h3 id="decompose-position-vector3-quaternion-quaternion-scale-vector3-this" tabindex="-1"><a class="header-anchor" href="#decompose-position-vector3-quaternion-quaternion-scale-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.decompose" target="_blank" rel="noopener noreferrer">decompose<ExternalLinkIcon/></a> ( position : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, quaternion : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, scale : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵分解到给定的平移<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">position<ExternalLinkIcon/></a> ,旋转 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">quaternion<ExternalLinkIcon/></a>，缩放<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">scale<ExternalLinkIcon/></a>分量中。</p>
<p>注意：并非所有矩阵都可以通过这种方式分解。 例如，如果一个对象有一个非均匀缩放的父对象，那么该对象的世界矩阵可能是不可分解的，这种方法可能不合适。</p>
<h3 id="determinant-float" tabindex="-1"><a class="header-anchor" href="#determinant-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.determinant" target="_blank" rel="noopener noreferrer">determinant<ExternalLinkIcon/></a> () : Float</h3>
<p>计算并返回矩阵的行列式<a href="https://en.wikipedia.org/wiki/Determinant" target="_blank" rel="noopener noreferrer">determinant<ExternalLinkIcon/></a> 。</p>
<p>基于这个的方法概述<a href="http://www.euclideanspace.com/maths/algebra/matrix/functions/inverse/fourD/index.htm" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>。</p>
<h3 id="equals-m-matrix4-boolean" tabindex="-1"><a class="header-anchor" href="#equals-m-matrix4-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>如果矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> 与当前矩阵所有对应元素相同则返回true。</p>
<h3 id="extractbasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" tabindex="-1"><a class="header-anchor" href="#extractbasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.extractBasis" target="_blank" rel="noopener noreferrer">extractBasis<ExternalLinkIcon/></a> ( xAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, yAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, zAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵的基向量<a href="https://en.wikipedia.org/wiki/Basis_(linear_algebra)" target="_blank" rel="noopener noreferrer">basis<ExternalLinkIcon/></a>提取到指定的3个轴向量中。 如果矩阵如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span>
e<span class="token punctuation">,</span> f<span class="token punctuation">,</span> g<span class="token punctuation">,</span> h<span class="token punctuation">,</span>
i<span class="token punctuation">,</span> j<span class="token punctuation">,</span> k<span class="token punctuation">,</span> l<span class="token punctuation">,</span>
m<span class="token punctuation">,</span> n<span class="token punctuation">,</span> o<span class="token punctuation">,</span> p
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后x轴y轴z轴被设为：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>xAxis <span class="token operator">=</span> <span class="token punctuation">(</span>a<span class="token punctuation">,</span> e<span class="token punctuation">,</span> i<span class="token punctuation">)</span>
yAxis <span class="token operator">=</span> <span class="token punctuation">(</span>b<span class="token punctuation">,</span> f<span class="token punctuation">,</span> j<span class="token punctuation">)</span>
zAxis <span class="token operator">=</span> <span class="token punctuation">(</span>c<span class="token punctuation">,</span> g<span class="token punctuation">,</span> k<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="extractrotation-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#extractrotation-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.extractRotation" target="_blank" rel="noopener noreferrer">extractRotation<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将给定矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的旋转分量提取到该矩阵的旋转分量中。</p>
<h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 用来存储设置元素数据的数组
offset - (可选参数) 数组的偏移量，默认值为 0。</p>
<p>使用基于列优先格式<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>的数组来设置该矩阵。</p>
<h3 id="invert-this" tabindex="-1"><a class="header-anchor" href="#invert-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.invert" target="_blank" rel="noopener noreferrer">invert<ExternalLinkIcon/></a> () : this</h3>
<p>将当前矩阵翻转为它的逆矩阵，使用 <a href="https://en.wikipedia.org/wiki/Invertible_matrix#Analytic_solution" target="_blank" rel="noopener noreferrer">analytic method<ExternalLinkIcon/></a> 解析方式。你不能对行或列为 0 的矩阵进行翻转，如果你尝试这样做，该方法将生成一个零矩阵。</p>
<h3 id="getmaxscaleonaxis-float" tabindex="-1"><a class="header-anchor" href="#getmaxscaleonaxis-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.getMaxScaleOnAxis" target="_blank" rel="noopener noreferrer">getMaxScaleOnAxis<ExternalLinkIcon/></a> () : Float</h3>
<p>获取3个轴方向的最大缩放值。</p>
<h3 id="identity-this" tabindex="-1"><a class="header-anchor" href="#identity-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.identity" target="_blank" rel="noopener noreferrer">identity<ExternalLinkIcon/></a> () : this</h3>
<p>将当前矩阵重置为单位矩阵<a href="https://en.wikipedia.org/wiki/Identity_matrix" target="_blank" rel="noopener noreferrer">identity matrix<ExternalLinkIcon/></a>。</p>
<h3 id="lookat-eye-vector3-target-vector3-up-vector3-this" tabindex="-1"><a class="header-anchor" href="#lookat-eye-vector3-target-vector3-up-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.lookAt" target="_blank" rel="noopener noreferrer">lookAt<ExternalLinkIcon/></a> ( eye : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, up : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>构造一个旋转矩阵，从<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">eye<ExternalLinkIcon/></a> 指向 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a>，由向量 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">up<ExternalLinkIcon/></a> 定向。</p>
<h3 id="makerotationaxis-axis-vector3-theta-float-this" tabindex="-1"><a class="header-anchor" href="#makerotationaxis-axis-vector3-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationAxis" target="_blank" rel="noopener noreferrer">makeRotationAxis<ExternalLinkIcon/></a> ( axis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, theta : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">axis<ExternalLinkIcon/></a> — 旋转轴，需要被归一化。
theta — 旋转量（弧度）。</p>
<p>设置当前矩阵为围绕轴 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">axis<ExternalLinkIcon/></a> 旋转量为 theta弧度。
这是一种有点争议但在数学上可以替代通过四元数<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternions<ExternalLinkIcon/></a>旋转的办法。 请参阅此处<a href="https://www.gamedev.net/articles/programming/math-and-physics/do-we-really-need-quaternions-r1199" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>的讨论。</p>
<h3 id="makebasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" tabindex="-1"><a class="header-anchor" href="#makebasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeBasis" target="_blank" rel="noopener noreferrer">makeBasis<ExternalLinkIcon/></a> ( xAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, yAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, zAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>通过给定的三个向量设置该矩阵为基矩阵<a href="https://en.wikipedia.org/wiki/Basis_(linear_algebra)" target="_blank" rel="noopener noreferrer">basis<ExternalLinkIcon/></a>：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>xAxis<span class="token punctuation">.</span>x<span class="token punctuation">,</span> yAxis<span class="token punctuation">.</span>x<span class="token punctuation">,</span> zAxis<span class="token punctuation">.</span>x<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
xAxis<span class="token punctuation">.</span>y<span class="token punctuation">,</span> yAxis<span class="token punctuation">.</span>y<span class="token punctuation">,</span> zAxis<span class="token punctuation">.</span>y<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
xAxis<span class="token punctuation">.</span>z<span class="token punctuation">,</span> yAxis<span class="token punctuation">.</span>z<span class="token punctuation">,</span> zAxis<span class="token punctuation">.</span>z<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span>       <span class="token number">0</span><span class="token punctuation">,</span>       <span class="token number">0</span><span class="token punctuation">,</span>       <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makeperspective-left-float-right-float-top-float-bottom-float-near-float-far-float-this" tabindex="-1"><a class="header-anchor" href="#makeperspective-left-float-right-float-top-float-bottom-float-near-float-far-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makePerspective" target="_blank" rel="noopener noreferrer">makePerspective<ExternalLinkIcon/></a> ( left : Float, right : Float, top : Float, bottom : Float, near : Float, far : Float ) : this</h3>
<p>创建一个透视投影矩阵<a href="https://en.wikipedia.org/wiki/3D_projection#Perspective_projection" target="_blank" rel="noopener noreferrer">perspective projection<ExternalLinkIcon/></a>。 在引擎内部由<a href="https://threejs.org/docs/index.html#api/zh/cameras/PerspectiveCamera.updateProjectionMatrix" target="_blank" rel="noopener noreferrer">PerspectiveCamera.updateProjectionMatrix<ExternalLinkIcon/></a>()使用。</p>
<h3 id="makeorthographic-left-float-right-float-top-float-bottom-float-near-float-far-float-this" tabindex="-1"><a class="header-anchor" href="#makeorthographic-left-float-right-float-top-float-bottom-float-near-float-far-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeOrthographic" target="_blank" rel="noopener noreferrer">makeOrthographic<ExternalLinkIcon/></a> ( left : Float, right : Float, top : Float, bottom : Float, near : Float, far : Float ) : this</h3>
<p>创建一个正交投影矩阵<a href="https://en.wikipedia.org/wiki/Orthographic_projection" target="_blank" rel="noopener noreferrer">orthographic projection<ExternalLinkIcon/></a>。 在引擎内部由<a href="https://threejs.org/docs/index.html#api/zh/cameras/OrthographicCamera.updateProjectionMatrix" target="_blank" rel="noopener noreferrer">OrthographicCamera.updateProjectionMatrix<ExternalLinkIcon/></a>()使用。</p>
<h3 id="makerotationfromeuler-euler-euler-this" tabindex="-1"><a class="header-anchor" href="#makerotationfromeuler-euler-euler-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationFromEuler" target="_blank" rel="noopener noreferrer">makeRotationFromEuler<ExternalLinkIcon/></a> ( euler : <a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a> ) : this</h3>
<p>将传入的欧拉角转换为该矩阵的旋转分量(左上角的3x3矩阵)。 矩阵的其余部分被设为单位矩阵。根据欧拉角<a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">euler<ExternalLinkIcon/></a>的旋转顺序<a href="https://threejs.org/docs/index.html#api/zh/math/Euler.order" target="_blank" rel="noopener noreferrer">order<ExternalLinkIcon/></a>，总共有六种可能的结果。 详细信息，请参阅本页<a href="https://en.wikipedia.org/wiki/Euler_angles#Rotation_matrix" target="_blank" rel="noopener noreferrer">this page<ExternalLinkIcon/></a>。</p>
<h3 id="makerotationfromquaternion-q-quaternion-this" tabindex="-1"><a class="header-anchor" href="#makerotationfromquaternion-q-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationFromQuaternion" target="_blank" rel="noopener noreferrer">makeRotationFromQuaternion<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>将这个矩阵的旋转分量设置为四元数<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a>指定的旋转，如下链接所诉<a href="https://en.wikipedia.org/wiki/Rotation_matrix#Quaternion" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>。 矩阵的其余部分被设为单位矩阵。因此，给定四元数<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> = w + xi + yj + zk，得到的矩阵为:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token number">1</span><span class="token operator">-</span>2y²<span class="token operator">-</span>2z²    2xy<span class="token operator">-</span>2zw    2xz<span class="token operator">+</span>2yw    <span class="token number">0</span>
2xy<span class="token operator">+</span>2zw      <span class="token number">1</span><span class="token operator">-</span>2x²<span class="token operator">-</span>2z²  2yz<span class="token operator">-</span>2xw    <span class="token number">0</span>
2xz<span class="token operator">-</span>2yw      2yz<span class="token operator">+</span>2xw    <span class="token number">1</span><span class="token operator">-</span>2x²<span class="token operator">-</span>2y²  <span class="token number">0</span>
<span class="token number">0</span>            <span class="token number">0</span>          <span class="token number">0</span>          <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makerotationx-theta-float-this" tabindex="-1"><a class="header-anchor" href="#makerotationx-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationX" target="_blank" rel="noopener noreferrer">makeRotationX<ExternalLinkIcon/></a> ( theta : Float ) : this</h3>
<p>theta — Rotation angle in radians.</p>
<p>把该矩阵设置为绕x轴旋转弧度theta (θ)大小的矩阵。 结果如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token number">1</span> <span class="token number">0</span>      <span class="token number">0</span>        <span class="token number">0</span>
<span class="token number">0</span> <span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token operator">-</span><span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span>  <span class="token number">0</span>
<span class="token number">0</span> <span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span>   <span class="token number">0</span>
<span class="token number">0</span> <span class="token number">0</span>      <span class="token number">0</span>        <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makerotationy-theta-float-this" tabindex="-1"><a class="header-anchor" href="#makerotationy-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationY" target="_blank" rel="noopener noreferrer">makeRotationY<ExternalLinkIcon/></a> ( theta : Float ) : this</h3>
<p>theta — Rotation angle in radians.</p>
<p>把该矩阵设置为绕Y轴旋转弧度theta (θ)大小的矩阵。 结果如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span>  <span class="token number">0</span> <span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token number">0</span>
<span class="token number">0</span>       <span class="token number">1</span> <span class="token number">0</span>      <span class="token number">0</span>
<span class="token operator">-</span><span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token number">0</span> <span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token number">0</span>
<span class="token number">0</span>       <span class="token number">0</span> <span class="token number">0</span>      <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makerotationz-theta-float-this" tabindex="-1"><a class="header-anchor" href="#makerotationz-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeRotationZ" target="_blank" rel="noopener noreferrer">makeRotationZ<ExternalLinkIcon/></a> ( theta : Float ) : this</h3>
<p>theta — Rotation angle in radians.</p>
<p>把该矩阵设置为绕z轴旋转弧度theta (θ)大小的矩阵。 结果如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token operator">-</span><span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token number">0</span> <span class="token number">0</span>
<span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span>  <span class="token number">0</span> <span class="token number">0</span>
<span class="token number">0</span>      <span class="token number">0</span>       <span class="token number">1</span> <span class="token number">0</span>
<span class="token number">0</span>      <span class="token number">0</span>       <span class="token number">0</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makescale-x-float-y-float-z-float-this" tabindex="-1"><a class="header-anchor" href="#makescale-x-float-y-float-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeScale" target="_blank" rel="noopener noreferrer">makeScale<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this</h3>
<p>x - 在X轴方向的缩放比。
y - 在Y轴方向的缩放比。
z - 在Z轴方向的缩放比。</p>
<p>将这个矩阵设置为缩放变换:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>x<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> y<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> z<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makeshear-x-float-y-float-z-float-this" tabindex="-1"><a class="header-anchor" href="#makeshear-x-float-y-float-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeShear" target="_blank" rel="noopener noreferrer">makeShear<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this</h3>
<p>x - 在X轴上剪切的量。
y - 在Y轴上剪切的量。
z - 在Z轴上剪切的量。</p>
<p>将此矩阵设置为剪切变换:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token number">1</span><span class="token punctuation">,</span> y<span class="token punctuation">,</span> z<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
x<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> z<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
x<span class="token punctuation">,</span> y<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="maketranslation-x-float-y-float-z-float-this" tabindex="-1"><a class="header-anchor" href="#maketranslation-x-float-y-float-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.makeTranslation" target="_blank" rel="noopener noreferrer">makeTranslation<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this</h3>
<p>x - 在X轴上的平移量。
y - 在Y轴上的平移量。
z - 在Z轴上的平移量。</p>
<p>设置该矩阵为平移变换：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> x<span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> y<span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> z<span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="multiply-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#multiply-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将当前矩阵乘以矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>。</p>
<h3 id="multiplymatrices-a-matrix4-b-matrix4-this" tabindex="-1"><a class="header-anchor" href="#multiplymatrices-a-matrix4-b-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.multiplyMatrices" target="_blank" rel="noopener noreferrer">multiplyMatrices<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>设置当前矩阵为矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> x 矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="multiplyscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#multiplyscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.multiplyScalar" target="_blank" rel="noopener noreferrer">multiplyScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>当前矩阵所有的元素乘以该缩放值<strong>s</strong></p>
<h3 id="premultiply-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#premultiply-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.premultiply" target="_blank" rel="noopener noreferrer">premultiply<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>乘以当前矩阵。</p>
<h3 id="scale-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#scale-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.scale" target="_blank" rel="noopener noreferrer">scale<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该矩阵的列向量乘以对应向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的分量。</p>
<h3 id="set-n11-float-n12-float-n13-float-n14-float-n21-float-n22-float-n23-float-n24-float-n31-float-n32-float-n33-float-n34-float-n41-float-n42-float-n43-float-n44-float-this" tabindex="-1"><a class="header-anchor" href="#set-n11-float-n12-float-n13-float-n14-float-n21-float-n22-float-n23-float-n24-float-n31-float-n32-float-n33-float-n34-float-n41-float-n42-float-n43-float-n44-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( n11 : Float, n12 : Float, n13 : Float, n14 : Float, n21 : Float, n22 : Float, n23 : Float, n24 : Float, n31 : Float, n32 : Float, n33 : Float, n34 : Float, n41 : Float, n42 : Float, n43 : Float, n44 : Float ) : this</h3>
<p>以行优先的格式将传入的数值设置给该矩阵中的元素<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a>。</p>
<h3 id="setfrommatrix3-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrix3-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.setFromMatrix3" target="_blank" rel="noopener noreferrer">setFromMatrix3<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>根据参数 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> 的值，设置当前矩阵左上 3x3 的矩阵值。</p>
<h3 id="setposition-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#setposition-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.setPosition" target="_blank" rel="noopener noreferrer">setPosition<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<h3 id="setposition-x-float-y-float-z-float-this-optional-api" tabindex="-1"><a class="header-anchor" href="#setposition-x-float-y-float-z-float-this-optional-api" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.setPosition" target="_blank" rel="noopener noreferrer">setPosition<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this // optional API</h3>
<p>取传入参数v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>中值设置该矩阵的位置分量，不影响该矩阵的其余部分——即，如果该矩阵当前为:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span>
e<span class="token punctuation">,</span> f<span class="token punctuation">,</span> g<span class="token punctuation">,</span> h<span class="token punctuation">,</span>
i<span class="token punctuation">,</span> j<span class="token punctuation">,</span> k<span class="token punctuation">,</span> l<span class="token punctuation">,</span>
m<span class="token punctuation">,</span> n<span class="token punctuation">,</span> o<span class="token punctuation">,</span> p
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>变成:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> v<span class="token punctuation">.</span>x<span class="token punctuation">,</span>
e<span class="token punctuation">,</span> f<span class="token punctuation">,</span> g<span class="token punctuation">,</span> v<span class="token punctuation">.</span>y<span class="token punctuation">,</span>
i<span class="token punctuation">,</span> j<span class="token punctuation">,</span> k<span class="token punctuation">,</span> v<span class="token punctuation">.</span>z<span class="token punctuation">,</span>
m<span class="token punctuation">,</span> n<span class="token punctuation">,</span> o<span class="token punctuation">,</span> p
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - (可选参数) 存储矩阵元素的数组，如果未指定会创建一个新的数组。
offset - (可选参数) 存放矩阵元素数组的偏移量。</p>
<p>使用列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>格式将此矩阵的元素写入数组中。</p>
<h3 id="transpose-this" tabindex="-1"><a class="header-anchor" href="#transpose-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4.transpose" target="_blank" rel="noopener noreferrer">transpose<ExternalLinkIcon/></a> () : this</h3>
<p>将该矩阵转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">Transposes<ExternalLinkIcon/></a>。</p>
</div></template>


