<template><div><h1 id="球坐标-spherical" tabindex="-1"><a class="header-anchor" href="#球坐标-spherical" aria-hidden="true">#</a> 球坐标（Spherical）</h1>
<p>一个点的<a href="https://en.wikipedia.org/wiki/Spherical_coordinate_system" target="_blank" rel="noopener noreferrer">spherical coordinates<ExternalLinkIcon/></a>（球坐标）。</p>
<h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="spherical-radius-float-phi-float-theta-float" tabindex="-1"><a class="header-anchor" href="#spherical-radius-float-phi-float-theta-float" aria-hidden="true">#</a> Spherical( radius : Float, phi : Float, theta : Float )</h3>
<p>radius - 半径值，或者说从该点到原点的 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a>（欧几里得距离，即直线距离）。默认值为<strong>1.0</strong>。
phi - 与 y (up) 轴的极角（以弧度为单位）。 默认值为 <strong>0</strong>。
theta - 绕 y (up) 轴的赤道角(方位角)（以弧度为单位）。 默认值为 <strong>0</strong>。</p>
<p>极角（phi）位于正 y 轴和负 y 轴上。赤道角(方位角)（theta）从正 z 开始。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="radius-float" tabindex="-1"><a class="header-anchor" href="#radius-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a> : Float</h3>
<h3 id="phi-float" tabindex="-1"><a class="header-anchor" href="#phi-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a> : Float</h3>
<h3 id="theta-float" tabindex="-1"><a class="header-anchor" href="#theta-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a> : Float</h3>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="clone-spherical" tabindex="-1"><a class="header-anchor" href="#clone-spherical" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">Spherical<ExternalLinkIcon/></a></h3>
<p>返回一个新的球坐标，新的球坐标与该球坐标具有相同的 <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>。</p>
<h3 id="copy-s-spherical-this" tabindex="-1"><a class="header-anchor" href="#copy-s-spherical-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( s : <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">Spherical<ExternalLinkIcon/></a> ) : this</h3>
<p>复制所传入的球坐标的<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a> 和<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>属性到该球坐标中。</p>
<h3 id="makesafe-this" tabindex="-1"><a class="header-anchor" href="#makesafe-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.makeSafe" target="_blank" rel="noopener noreferrer">makeSafe<ExternalLinkIcon/></a> () : this</h3>
<p>将极角 <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a> 的值限制在0.000001 和 π - 0.000001 之间。</p>
<h3 id="set-radius-float-phi-float-theta-float-this" tabindex="-1"><a class="header-anchor" href="#set-radius-float-phi-float-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( radius : Float, phi : Float, theta : Float ) : this</h3>
<p>设置球坐标中<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a> 属性的值。</p>
<h3 id="setfromvector3-vec3-vector3-this" tabindex="-1"><a class="header-anchor" href="#setfromvector3-vec3-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.setFromVector3" target="_blank" rel="noopener noreferrer">setFromVector3<ExternalLinkIcon/></a> ( vec3 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>从<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>中设置球坐标的<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>值。</p>
<h3 id="setfromcartesiancoords-x-float-y-float-z-float-this" tabindex="-1"><a class="header-anchor" href="#setfromcartesiancoords-x-float-y-float-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.setFromCartesianCoords" target="_blank" rel="noopener noreferrer">setFromCartesianCoords<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this</h3>
<p>从笛卡尔坐标系中设置球坐标的<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.phi" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical.theta" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>值。</p>
</div></template>


