<template><div><h1 id="四维向量-vector4" tabindex="-1"><a class="header-anchor" href="#四维向量-vector4" aria-hidden="true">#</a> 四维向量（Vector4）</h1>
<p>该类表示的是一个三维向量（4D <a href="https://en.wikipedia.org/wiki/Vector_space" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a>）。 一个四维向量表示的是一个有顺序的、四个为一组的数字组合（标记为x、y和z）， 可被用来表示很多事物，例如：</p>
<ul>
<li>一个位于四维空间中的点。</li>
<li>一个在四维空间中的方向与长度的定义。在three.js中，长度总是从(0, 0, 0, 0)到(x, y, z, w)的 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a>（欧几里德距离，即直线距离）， 方向也是从(0, 0, 0, 0)到(x, y, z, w)的方向。</li>
<li>任意的、有顺序的、四个为一组的数字组合。</li>
</ul>
<p>其他的一些事物也可以使用四维向量进行表示，但以上这些是它在three.js中的常用用途。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> a <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Vector4</span><span class="token punctuation">(</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//no arguments; will be initialised to (0, 0, 0, 1) const b = new THREE.Vector4( ); const d = a.dot( b );</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>对 Vector4 实例进行遍历将按相应的顺序生成它的分量 (x, y, z, w)。</p>
<h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="vector4-x-float-y-float-z-float-w-float" tabindex="-1"><a class="header-anchor" href="#vector4-x-float-y-float-z-float-w-float" aria-hidden="true">#</a> Vector4( x : Float, y : Float, z : Float, w : Float )</h3>
<p>x - 向量的x值，默认为<strong>0</strong>。
y - 向量的y值，默认为<strong>0</strong>。
z - 向量的z值，默认为<strong>0</strong>。
w - 向量的w值，默认为<strong>1</strong>。</p>
<p>创建一个新的Vector4。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="isvector4-boolean" tabindex="-1"><a class="header-anchor" href="#isvector4-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.isVector4" target="_blank" rel="noopener noreferrer">isVector4<ExternalLinkIcon/></a> : Boolean</h3>
<p>Read-only flag to check if a given object is of type Vector4.</p>
<h3 id="x-float" tabindex="-1"><a class="header-anchor" href="#x-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> : Float</h3>
<h3 id="y-float" tabindex="-1"><a class="header-anchor" href="#y-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> : Float</h3>
<h3 id="z-float" tabindex="-1"><a class="header-anchor" href="#z-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> : Float</h3>
<h3 id="w-float" tabindex="-1"><a class="header-anchor" href="#w-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> : Float</h3>
<h3 id="width-float" tabindex="-1"><a class="header-anchor" href="#width-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.width" target="_blank" rel="noopener noreferrer">width<ExternalLinkIcon/></a> : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>的别名。</p>
<h3 id="height-float" tabindex="-1"><a class="header-anchor" href="#height-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.height" target="_blank" rel="noopener noreferrer">height<ExternalLinkIcon/></a> : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>的别名。</p>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="add-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#add-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.add" target="_blank" rel="noopener noreferrer">add<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>将传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>和这个向量相加。</p>
<h3 id="addscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.addScalar" target="_blank" rel="noopener noreferrer">addScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将传入的标量s和这个向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值相加。</p>
<h3 id="addscaledvector-v-vector4-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscaledvector-v-vector4-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.addScaledVector" target="_blank" rel="noopener noreferrer">addScaledVector<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, s : Float ) : this</h3>
<p>将所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>与s相乘所得的乘积和这个向量相加。</p>
<h3 id="addvectors-a-vector4-b-vector4-this" tabindex="-1"><a class="header-anchor" href="#addvectors-a-vector4-b-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.addVectors" target="_blank" rel="noopener noreferrer">addVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> + <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>.</p>
<h3 id="applymatrix4-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量乘以四阶矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>。</p>
<h3 id="ceil-this" tabindex="-1"><a class="header-anchor" href="#ceil-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.ceil" target="_blank" rel="noopener noreferrer">ceil<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>分量、 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>分量以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>分量向上取整为最接近的整数。</p>
<h3 id="clamp-min-vector4-max-vector4-this" tabindex="-1"><a class="header-anchor" href="#clamp-min-vector4-max-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.clamp" target="_blank" rel="noopener noreferrer">clamp<ExternalLinkIcon/></a> ( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - 在限制范围内，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值的最小值
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - 在限制范围内，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值的最大值</p>
<p>如果该向量的x值、y值、z值或w值大于限制范围内最大x值、y值、z值或w值，则该值将会被所对应的值取代。</p>
<p>如果该向量的x值、y值、z值或w值小于限制范围内最小x值、y值、z值或w值，则该值将会被所对应的值取代。</p>
<h3 id="clamplength-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clamplength-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.clampLength" target="_blank" rel="noopener noreferrer">clampLength<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 长度将被限制为的最小值
max - 长度将被限制为的最大值</p>
<p>如果向量长度大于最大值，则它将会被最大值所取代。</p>
<p>如果向量长度小于最小值，则它将会被最小值所取代。</p>
<h3 id="clampscalar-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clampscalar-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.clampScalar" target="_blank" rel="noopener noreferrer">clampScalar<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 分量将被限制为的最小值
max - 分量将被限制为的最大值</p>
<p>如果该向量的x值、y值、z值或w值大于最大值，则它们将被最大值所取代。</p>
<p>如果该向量的x值、y值、z值或w值小于最小值，则它们将被最小值所取代。</p>
<h3 id="clone-vector4" tabindex="-1"><a class="header-anchor" href="#clone-vector4" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a></h3>
<p>返回一个新的Vector4，其具有和当前这个向量相同的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>。</p>
<h3 id="copy-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#copy-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>将所传入Vector4的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>属性复制给这一Vector4。</p>
<h3 id="dividescalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#dividescalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.divideScalar" target="_blank" rel="noopener noreferrer">divideScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量除以标量s。</p>
<h3 id="dot-v-vector4-float" tabindex="-1"><a class="header-anchor" href="#dot-v-vector4-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.dot" target="_blank" rel="noopener noreferrer">dot<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector和所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> 的点积（<a href="https://en.wikipedia.org/wiki/Dot_product" target="_blank" rel="noopener noreferrer">dot product<ExternalLinkIcon/></a>）。</p>
<h3 id="equals-v-vector4-boolean" tabindex="-1"><a class="header-anchor" href="#equals-v-vector4-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>检查该向量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的严格相等性。</p>
<h3 id="floor-this" tabindex="-1"><a class="header-anchor" href="#floor-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.floor" target="_blank" rel="noopener noreferrer">floor<ExternalLinkIcon/></a> () : this</h3>
<p>向量的分量向下取整为最接近的整数值。</p>
<h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 来源矩阵。
offset - （可选）在数组中的元素偏移量，默认值为0。</p>
<p>设置向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值为array[ offset + 0 ]，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值为array[ offset + 1 ]， <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值为array[ offset + 2 ]，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w <ExternalLinkIcon/></a>值为array[ offset + 3 ]。</p>
<h3 id="frombufferattribute-attribute-bufferattribute-index-integer-this" tabindex="-1"><a class="header-anchor" href="#frombufferattribute-attribute-bufferattribute-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.fromBufferAttribute" target="_blank" rel="noopener noreferrer">fromBufferAttribute<ExternalLinkIcon/></a> ( attribute : <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">BufferAttribute<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> - 来源的attribute。
index - 在attribute中的索引。</p>
<p>从<a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a>中设置向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值。</p>
<h3 id="getcomponent-index-integer-float" tabindex="-1"><a class="header-anchor" href="#getcomponent-index-integer-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.getComponent" target="_blank" rel="noopener noreferrer">getComponent<ExternalLinkIcon/></a> ( index : Integer ) : Float</h3>
<p>index - 0, 1, 2 or 3.</p>
<p>如果index值为0返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值。
如果index值为1返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值。
如果index值为2返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值。
如果index值为3返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值。</p>
<h3 id="length-float" tabindex="-1"><a class="header-anchor" href="#length-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0, 0, 0) 到 (x, y, z, w)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）。</p>
<h3 id="manhattanlength-float" tabindex="-1"><a class="header-anchor" href="#manhattanlength-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.manhattanLength" target="_blank" rel="noopener noreferrer">manhattanLength<ExternalLinkIcon/></a> () : Float</h3>
<p>计算该向量的曼哈顿长度（<a href="http://en.wikipedia.org/wiki/Taxicab_geometry" target="_blank" rel="noopener noreferrer">Manhattan length<ExternalLinkIcon/></a>）。</p>
<h3 id="lengthsq-float" tabindex="-1"><a class="header-anchor" href="#lengthsq-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.lengthSq" target="_blank" rel="noopener noreferrer">lengthSq<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0, 0, 0)到(x, y, z, w)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）的平方。 如果你正在比较向量的长度，应当比较的是长度的平方，因为它的计算效率更高一些。</p>
<h3 id="lerp-v-vector4-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerp-v-vector4-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.lerp" target="_blank" rel="noopener noreferrer">lerp<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围通常在[0, 1]闭区间。</p>
<p>在该向量与传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>之间的线性插值，alpha是沿着线的长度的百分比 —— alpha = 0 时表示的是当前向量，alpha = 1 时表示的是所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="lerpvectors-v1-vector4-v2-vector4-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerpvectors-v1-vector4-v2-vector4-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.lerpVectors" target="_blank" rel="noopener noreferrer">lerpVectors<ExternalLinkIcon/></a> ( v1 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, v2 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a> - 起始的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围在[0, 1]闭区间。</p>
<p>将此向量设置为在<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>之间进行线性插值的向量， 其中alpha为两个向量之间连线的长度的百分比 —— alpha = 0 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>，alpha = 1 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>。</p>
<h3 id="negate-this" tabindex="-1"><a class="header-anchor" href="#negate-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.negate" target="_blank" rel="noopener noreferrer">negate<ExternalLinkIcon/></a> () : this</h3>
<p>向量取反，即： x = -x, y = -y, z = -z , w = -w。</p>
<h3 id="normalize-this" tabindex="-1"><a class="header-anchor" href="#normalize-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.normalize" target="_blank" rel="noopener noreferrer">normalize<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量转换为单位向量（<a href="https://en.wikipedia.org/wiki/Unit_vector" target="_blank" rel="noopener noreferrer">unit vector<ExternalLinkIcon/></a>）， 也就是说，将该向量的方向设置为和原向量相同，但是其长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为1。</p>
<h3 id="max-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#max-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值、y值、z值或w值小于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值、y值、z值或w值， 则将该值替换为对应的最大值。</p>
<h3 id="min-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#min-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值、y值、z值或w值大于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值、y值、z值或w值， 则将该值替换为对应的最小值。</p>
<h3 id="multiply-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#multiply-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量与所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>进行相乘。</p>
<h3 id="multiplyscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#multiplyscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.multiplyScalar" target="_blank" rel="noopener noreferrer">multiplyScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量与所传入的标量s进行相乘。</p>
<h3 id="round-this" tabindex="-1"><a class="header-anchor" href="#round-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.round" target="_blank" rel="noopener noreferrer">round<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的分量四舍五入取整为最接近的整数值。</p>
<h3 id="roundtozero-this" tabindex="-1"><a class="header-anchor" href="#roundtozero-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.roundToZero" target="_blank" rel="noopener noreferrer">roundToZero<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的分量朝向0取整数（若分量为负数则向上取整，若为正数则向下取整）</p>
<h3 id="set-x-float-y-float-z-float-w-float-this" tabindex="-1"><a class="header-anchor" href="#set-x-float-y-float-z-float-w-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float, w : Float ) : this</h3>
<p>设置该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>分量。</p>
<h3 id="setaxisanglefromquaternion-q-quaternion-this" tabindex="-1"><a class="header-anchor" href="#setaxisanglefromquaternion-q-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setAxisAngleFromQuaternion" target="_blank" rel="noopener noreferrer">setAxisAngleFromQuaternion<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> - 归一化的<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>（四元数）</p>
<p>将该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>分量设置为四元数的轴， <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>分量设置为四元数的角度。</p>
<h3 id="setaxisanglefromrotationmatrix-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#setaxisanglefromrotationmatrix-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setAxisAngleFromRotationMatrix" target="_blank" rel="noopener noreferrer">setAxisAngleFromRotationMatrix<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> - 一个<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>（四阶矩阵），其左上角3x3的元素表示的是一个纯旋转矩。</p>
<p>将该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>设置为旋转轴，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>为角度。</p>
<h3 id="setcomponent-index-integer-value-float-this" tabindex="-1"><a class="header-anchor" href="#setcomponent-index-integer-value-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setComponent" target="_blank" rel="noopener noreferrer">setComponent<ExternalLinkIcon/></a> ( index : Integer, value : Float ) : this</h3>
<p>index - 0、1、2 或 3。
value - Float</p>
<p>若index为 0 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> 值为 value。
若index为 1 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> 值为 value。
若index为 2 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 值为 value。
若index为 3 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> 值为 value。</p>
<h3 id="setlength-l-float-this" tabindex="-1"><a class="header-anchor" href="#setlength-l-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setLength" target="_blank" rel="noopener noreferrer">setLength<ExternalLinkIcon/></a> ( l : Float ) : this</h3>
<p>将该向量的方向设置为和原向量相同，但是长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为l。</p>
<h3 id="setscalar-scalar-float-this" tabindex="-1"><a class="header-anchor" href="#setscalar-scalar-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setScalar" target="_blank" rel="noopener noreferrer">setScalar<ExternalLinkIcon/></a> ( scalar : Float ) : this</h3>
<p>将该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>同时设置为等于传入的scalar。</p>
<h3 id="setx-x-float-this" tabindex="-1"><a class="header-anchor" href="#setx-x-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setX" target="_blank" rel="noopener noreferrer">setX<ExternalLinkIcon/></a> ( x : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值替换为x。</p>
<h3 id="sety-y-float-this" tabindex="-1"><a class="header-anchor" href="#sety-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setY" target="_blank" rel="noopener noreferrer">setY<ExternalLinkIcon/></a> ( y : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值替换为y。</p>
<h3 id="setz-z-float-this" tabindex="-1"><a class="header-anchor" href="#setz-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setZ" target="_blank" rel="noopener noreferrer">setZ<ExternalLinkIcon/></a> ( z : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值替换为z。</p>
<h3 id="setw-w-float-this" tabindex="-1"><a class="header-anchor" href="#setw-w-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.setW" target="_blank" rel="noopener noreferrer">setW<ExternalLinkIcon/></a> ( w : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>值替换为w。</p>
<h3 id="sub-v-vector4-this" tabindex="-1"><a class="header-anchor" href="#sub-v-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.sub" target="_blank" rel="noopener noreferrer">sub<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>从该向量减去向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="subscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#subscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.subScalar" target="_blank" rel="noopener noreferrer">subScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>从该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>分量中减去标量s。</p>
<h3 id="subvectors-a-vector4-b-vector4-this" tabindex="-1"><a class="header-anchor" href="#subvectors-a-vector4-b-vector4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.subVectors" target="_blank" rel="noopener noreferrer">subVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">Vector4<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector4" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - （可选）被用于存储向量的数组。如果这个值没有传入，则将创建一个新的数组。
offset - （可选） 数组中元素的偏移量。</p>
<p>返回一个数组[x, y, z, w]，或者将x、y、z和w复制到所传入的array中。</p>
<h3 id="random-this" tabindex="-1"><a class="header-anchor" href="#random-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector4.random" target="_blank" rel="noopener noreferrer">random<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量的每个分量(x、y、z、w)设置为介于 0 和 1 之间的伪随机数，不包括 1。</p>
</div></template>


