<template><div><h1 id="box2" tabindex="-1"><a class="header-anchor" href="#box2" aria-hidden="true">#</a> Box2</h1>
<p>表示二维空间中的一个轴对齐包围盒（axis-aligned bounding box，AABB）。</p>
<h2 id="构造函数-constructor" tabindex="-1"><a class="header-anchor" href="#构造函数-constructor" aria-hidden="true">#</a> 构造函数(Constructor)</h2>
<h3 id="box2-min-vector2-max-vector2" tabindex="-1"><a class="header-anchor" href="#box2-min-vector2-max-vector2" aria-hidden="true">#</a> Box2( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> )</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - (可选) <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> 表示该盒子的下边界(x, y)。默认值为( + Infinity, + Infinity )。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - (可选) <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> 表示该盒子的上边界(x, y)。默认值为( - Infinity, - Infinity )。</p>
<p>创建一个介于最小和最大值之间的Box2。</p>
<h2 id="属性-properties" tabindex="-1"><a class="header-anchor" href="#属性-properties" aria-hidden="true">#</a> 属性(Properties)</h2>
<h3 id="min-vector2" tabindex="-1"><a class="header-anchor" href="#min-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> 表示该盒子的下边界(x, y)。
默认值为( + Infinity, + Infinity )。</p>
<h3 id="max-vector2" tabindex="-1"><a class="header-anchor" href="#max-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> 表示该盒子的上边界(x, y)。
默认值为( - Infinity, - Infinity )。</p>
<h2 id="方法-methods" tabindex="-1"><a class="header-anchor" href="#方法-methods" aria-hidden="true">#</a> 方法(Methods)</h2>
<h3 id="clamppoint-point-vector2-target-vector2-vector2" tabindex="-1"><a class="header-anchor" href="#clamppoint-point-vector2-target-vector2-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.clampPoint" target="_blank" rel="noopener noreferrer">clampPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - clamp 的位置 (<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>)
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果会被复制到该二维向量中。</p>
<p>在该盒子范围内夹紧（<a href="https://en.wikipedia.org/wiki/Clamping_(graphics)" target="_blank" rel="noopener noreferrer">Clamps<ExternalLinkIcon/></a>）<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>。</p>
<h3 id="clone-box2" tabindex="-1"><a class="header-anchor" href="#clone-box2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a></h3>
<p>返回一个新的<a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a>，其<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a>与此盒子相同。</p>
<h3 id="containsbox-box-box2-boolean" tabindex="-1"><a class="header-anchor" href="#containsbox-box-box2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.containsBox" target="_blank" rel="noopener noreferrer">containsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 要检查是否被包含的盒子。</p>
<p>如果盒子包含整个被检查盒子，则返回true。如果两者重叠，
也会返回true。</p>
<h3 id="containspoint-point-vector2-boolean" tabindex="-1"><a class="header-anchor" href="#containspoint-point-vector2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.containsPoint" target="_blank" rel="noopener noreferrer">containsPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 要检查是否被包含的点<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>。</p>
<p>如果指定的点(<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>)位于盒子的边界内或边界上，则返回true。</p>
<h3 id="copy-box-box2-this" tabindex="-1"><a class="header-anchor" href="#copy-box-box2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : this</h3>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a>的<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Box2.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a>复制到此盒子中。</p>
<h3 id="distancetopoint-point-vector2-float" tabindex="-1"><a class="header-anchor" href="#distancetopoint-point-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.distanceToPoint" target="_blank" rel="noopener noreferrer">distanceToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 要测量距离的点(<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>)。</p>
<p>返回这个盒子的任何边缘到指定点的距离。如果这个点(<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>)位于这个盒子里，距离将是0。</p>
<h3 id="equals-box-box2-boolean" tabindex="-1"><a class="header-anchor" href="#equals-box-box2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 要对比的盒子</p>
<p>如果这个盒子和被对比盒子具有相同的上下边界，则返回true。</p>
<h3 id="expandbypoint-point-vector2-this" tabindex="-1"><a class="header-anchor" href="#expandbypoint-point-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.expandByPoint" target="_blank" rel="noopener noreferrer">expandByPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 应该被盒子包含的点。</p>
<p>扩展盒子的边界来包含该点。</p>
<h3 id="expandbyscalar-scalar-float-this" tabindex="-1"><a class="header-anchor" href="#expandbyscalar-scalar-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.expandByScalar" target="_blank" rel="noopener noreferrer">expandByScalar<ExternalLinkIcon/></a> ( scalar : Float ) : this</h3>
<p>scalar - 盒子扩展的距离。</p>
<p>在每个维度上扩展参数scalar所指定的距离，如果为负数，则盒子空间将收缩。</p>
<h3 id="expandbyvector-vector-vector2-this" tabindex="-1"><a class="header-anchor" href="#expandbyvector-vector-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.expandByVector" target="_blank" rel="noopener noreferrer">expandByVector<ExternalLinkIcon/></a> ( vector : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a> - 按照该向量扩展。</p>
<p>在每个维度中按vector的数值进行扩展。宽度在两个方向上的扩展将由vector的x分量确定， 高度在两个方向上的扩展则由y分量确定。</p>
<h3 id="getcenter-target-vector2-vector2" tabindex="-1"><a class="header-anchor" href="#getcenter-target-vector2-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.getCenter" target="_blank" rel="noopener noreferrer">getCenter<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将被复制到此二维向量中。</p>
<p>以二维向量形式返回盒子的中心点。</p>
<h3 id="getparameter-point-vector2-target-vector2-vector2" tabindex="-1"><a class="header-anchor" href="#getparameter-point-vector2-target-vector2-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.getParameter" target="_blank" rel="noopener noreferrer">getParameter<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 二维向量(<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>).
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将被复制到此二维向量中。</p>
<p>返回一个点作为此盒子的宽度和高度的比例。</p>
<h3 id="getsize-target-vector2-vector2" tabindex="-1"><a class="header-anchor" href="#getsize-target-vector2-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.getSize" target="_blank" rel="noopener noreferrer">getSize<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将被复制到此二维向量中。</p>
<p>返回此盒子的宽度和高度。</p>
<h3 id="intersect-box-box2-this" tabindex="-1"><a class="header-anchor" href="#intersect-box-box2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.intersect" target="_blank" rel="noopener noreferrer">intersect<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 要相交的盒子。</p>
<p>返回两者的相交后的盒子，并将相交后的盒子的上限设置为两者的上限中的较小者，将下限设置为两者的下限中的较大者。</p>
<h3 id="intersectsbox-box-box2-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsbox-box-box2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.intersectsBox" target="_blank" rel="noopener noreferrer">intersectsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 用来检查相交的盒子。</p>
<p>确定该盒子是否和其相交。</p>
<h3 id="isempty-boolean" tabindex="-1"><a class="header-anchor" href="#isempty-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.isEmpty" target="_blank" rel="noopener noreferrer">isEmpty<ExternalLinkIcon/></a> () : Boolean</h3>
<p>如果这个盒子包含0个顶点，则返回true。
请注意，一个下上边界相等的的盒子仍然包括一个点，一个两个边界共享的点。</p>
<h3 id="makeempty-this" tabindex="-1"><a class="header-anchor" href="#makeempty-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.makeEmpty" target="_blank" rel="noopener noreferrer">makeEmpty<ExternalLinkIcon/></a> () : this</h3>
<p>使此盒子为空。</p>
<h3 id="set-min-vector2-max-vector2-this" tabindex="-1"><a class="header-anchor" href="#set-min-vector2-max-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - (必须) 表示该盒子的下边界(x, y)。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - (必须) 表示该盒子的上边界(x, y)。</p>
<p>设置这个盒子的上下(x, y)的界限。
请注意，此方法仅复制给定对象的值。</p>
<h3 id="setfromcenterandsize-center-vector2-size-vector2-this" tabindex="-1"><a class="header-anchor" href="#setfromcenterandsize-center-vector2-size-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.setFromCenterAndSize" target="_blank" rel="noopener noreferrer">setFromCenterAndSize<ExternalLinkIcon/></a> ( center : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, size : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> - 盒子所要设置的中心位置。 (<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>).
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">size<ExternalLinkIcon/></a> - 盒子所要设置的x和y尺寸 (<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>).</p>
<p>使盒子的中心点位于<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>，并设置宽高为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">size<ExternalLinkIcon/></a>中指定的值。</p>
<h3 id="setfrompoints-points-array-this" tabindex="-1"><a class="header-anchor" href="#setfrompoints-points-array-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.setFromPoints" target="_blank" rel="noopener noreferrer">setFromPoints<ExternalLinkIcon/></a> ( points : Array ) : this</h3>
<p>points - 点的集合，由这些点确定的空间将被盒子包围。</p>
<p>设置这个盒子的上下边界，来包含所有设置在points参数中的点。</p>
<h3 id="translate-offset-vector2-this" tabindex="-1"><a class="header-anchor" href="#translate-offset-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.translate" target="_blank" rel="noopener noreferrer">translate<ExternalLinkIcon/></a> ( offset : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a> - 偏移方向和距离。</p>
<p>添加 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a> 到这个盒子的上下边界，实际上在2D空间移动这个盒子<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">offset<ExternalLinkIcon/></a>个单位。</p>
<h3 id="union-box-box2-this" tabindex="-1"><a class="header-anchor" href="#union-box-box2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Box2.union" target="_blank" rel="noopener noreferrer">union<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">Box2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将要与该盒子联合的盒子</p>
<p>在<a href="https://threejs.org/docs/index.html#api/zh/math/Box2" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a>参数的上边界和该盒子的上边界之间取较大者，而对两者的下边界取较小者，这样获得一个新的较大的联合盒子。</p>
</div></template>


