<template><div><h1 id="三维矩阵-matrix3" tabindex="-1"><a class="header-anchor" href="#三维矩阵-matrix3" aria-hidden="true">#</a> 三维矩阵（Matrix3）</h1>
<p>一个表示3X3矩阵<a href="https://en.wikipedia.org/wiki/Matrix_(mathematics)" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a>.的类。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> m <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Matrix3</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="注意行优先列优先的顺序。" tabindex="-1"><a class="header-anchor" href="#注意行优先列优先的顺序。" aria-hidden="true">#</a> 注意行优先列优先的顺序。</h2>
<p>set()方法参数采用行优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">row-major<ExternalLinkIcon/></a>， 而它们在内部是用列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>顺序存储在数组当中。</p>
<p>这意味着</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>m<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span> <span class="token number">11</span><span class="token punctuation">,</span> <span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token punctuation">,</span>
       <span class="token number">21</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">23</span><span class="token punctuation">,</span>
       <span class="token number">31</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">33</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>元素数组<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a>将存储为:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>m<span class="token punctuation">.</span>elements <span class="token operator">=</span> <span class="token punctuation">[</span> <span class="token number">11</span><span class="token punctuation">,</span> <span class="token number">21</span><span class="token punctuation">,</span> <span class="token number">31</span><span class="token punctuation">,</span>
              <span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span>
              <span class="token number">13</span><span class="token punctuation">,</span> <span class="token number">23</span><span class="token punctuation">,</span> <span class="token number">33</span> <span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在内部，所有的计算都是使用列优先顺序进行的。然而，由于实际的排序在数学上没有什么不同， 而且大多数人习惯于以行优先顺序考虑矩阵，所以three.js文档以行为主的顺序显示矩阵。 请记住，如果您正在阅读源代码，您必须对这里列出的任何矩阵进行转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">transpose<ExternalLinkIcon/></a>，以理解计算。</p>
<h2 id="constructor" tabindex="-1"><a class="header-anchor" href="#constructor" aria-hidden="true">#</a> Constructor</h2>
<h3 id="matrix3" tabindex="-1"><a class="header-anchor" href="#matrix3" aria-hidden="true">#</a> Matrix3()</h3>
<p>创建并初始化一个3X3的单位矩阵<a href="https://en.wikipedia.org/wiki/Identity_matrix" target="_blank" rel="noopener noreferrer">identity matrix<ExternalLinkIcon/></a>.</p>
<h2 id="属性-properties" tabindex="-1"><a class="header-anchor" href="#属性-properties" aria-hidden="true">#</a> 属性（Properties）</h2>
<h3 id="elements-array" tabindex="-1"><a class="header-anchor" href="#elements-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a> : Array</h3>
<p>矩阵列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>列表。</p>
<h2 id="方法-methods" tabindex="-1"><a class="header-anchor" href="#方法-methods" aria-hidden="true">#</a> 方法（Methods）</h2>
<h3 id="clone-matrix3" tabindex="-1"><a class="header-anchor" href="#clone-matrix3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a></h3>
<p>创建一个新的矩阵，元素 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.elements" target="_blank" rel="noopener noreferrer">elements<ExternalLinkIcon/></a> 与该矩阵相同。</p>
<h3 id="copy-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#copy-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的元素复制到当前矩阵中。</p>
<h3 id="determinant-float" tabindex="-1"><a class="header-anchor" href="#determinant-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.determinant" target="_blank" rel="noopener noreferrer">determinant<ExternalLinkIcon/></a> () : Float</h3>
<p>计算并返回矩阵的行列式<a href="https://en.wikipedia.org/wiki/Determinant" target="_blank" rel="noopener noreferrer">determinant<ExternalLinkIcon/></a> 。</p>
<h3 id="equals-m-matrix3-boolean" tabindex="-1"><a class="header-anchor" href="#equals-m-matrix3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>如果矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> 与当前矩阵所有对应元素相同则返回true。</p>
<h3 id="extractbasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" tabindex="-1"><a class="header-anchor" href="#extractbasis-xaxis-vector3-yaxis-vector3-zaxis-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.extractBasis" target="_blank" rel="noopener noreferrer">extractBasis<ExternalLinkIcon/></a> ( xAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, yAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, zAxis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该矩阵的基向量 <a href="https://en.wikipedia.org/wiki/Basis_(linear_algebra)" target="_blank" rel="noopener noreferrer">basis<ExternalLinkIcon/></a> 提取到提供的三个轴向中。如果该矩阵如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span>
d<span class="token punctuation">,</span> e<span class="token punctuation">,</span> f<span class="token punctuation">,</span>
g<span class="token punctuation">,</span> h<span class="token punctuation">,</span> i
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>那么 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">xAxis<ExternalLinkIcon/></a>, <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">yAxis<ExternalLinkIcon/></a>, <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">zAxis<ExternalLinkIcon/></a> 将会被设置为：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>xAxis <span class="token operator">=</span> <span class="token punctuation">(</span>a<span class="token punctuation">,</span> d<span class="token punctuation">,</span> g<span class="token punctuation">)</span>
yAxis <span class="token operator">=</span> <span class="token punctuation">(</span>b<span class="token punctuation">,</span> e<span class="token punctuation">,</span> h<span class="token punctuation">)</span>
zAxis <span class="token operator">=</span> <span class="token punctuation">(</span>c<span class="token punctuation">,</span> f<span class="token punctuation">,</span> i<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 用来存储设置元素数据的数组
offset - (可选参数) 数组的偏移量，默认值为 0。</p>
<p>使用基于列优先格式<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>的数组来设置该矩阵。</p>
<h3 id="invert-this" tabindex="-1"><a class="header-anchor" href="#invert-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.invert" target="_blank" rel="noopener noreferrer">invert<ExternalLinkIcon/></a> () : this</h3>
<p>将当前矩阵翻转为它的逆矩阵，使用 <a href="https://en.wikipedia.org/wiki/Invertible_matrix#Analytic_solution" target="_blank" rel="noopener noreferrer">analytic method<ExternalLinkIcon/></a> 解析方式。你不能对行或列为 0 的矩阵进行翻转，如果你尝试这样做，该方法将生成一个零矩阵。</p>
<h3 id="getnormalmatrix-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#getnormalmatrix-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.getNormalMatrix" target="_blank" rel="noopener noreferrer">getNormalMatrix<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a></p>
<p>将这个矩阵设置为给定矩阵的正规矩阵<a href="https://en.wikipedia.org/wiki/Normal_matrix" target="_blank" rel="noopener noreferrer">normal matrix<ExternalLinkIcon/></a>（左上角的3x3）。 正规矩阵是矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的逆矩阵<a href="https://en.wikipedia.org/wiki/Invertible_matrix" target="_blank" rel="noopener noreferrer">inverse<ExternalLinkIcon/></a> 的转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">transpose<ExternalLinkIcon/></a>。</p>
<h3 id="identity-this" tabindex="-1"><a class="header-anchor" href="#identity-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.identity" target="_blank" rel="noopener noreferrer">identity<ExternalLinkIcon/></a> () : this</h3>
<p>将此矩阵重置为3x3单位矩阵:<code v-pre>1, 0, 0 0, 1, 0 0, 0, 1</code></p>
<h3 id="makerotation-theta-float-this" tabindex="-1"><a class="header-anchor" href="#makerotation-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.makeRotation" target="_blank" rel="noopener noreferrer">makeRotation<ExternalLinkIcon/></a> ( theta : Float ) : this</h3>
<p>theta — 弧度表示的旋转角。 逆时针旋转为正值</p>
<p>将这个矩阵设置为一个二维旋转变换，单位为弧度。 矩阵的结果将是:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token operator">-</span><span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token number">0</span>
<span class="token function">sin</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span> <span class="token function">cos</span><span class="token punctuation">(</span>θ<span class="token punctuation">)</span>  <span class="token number">0</span>
<span class="token number">0</span>      <span class="token number">0</span>       <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="makescale-x-float-y-float-this" tabindex="-1"><a class="header-anchor" href="#makescale-x-float-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.makeScale" target="_blank" rel="noopener noreferrer">makeScale<ExternalLinkIcon/></a> ( x : Float, y : Float ) : this</h3>
<p>x - x轴缩放范围.
y - y轴缩放范围.
将这个矩阵设置为2维缩放矩阵:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>x<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> y<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="maketranslation-x-float-y-float-this" tabindex="-1"><a class="header-anchor" href="#maketranslation-x-float-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.makeTranslation" target="_blank" rel="noopener noreferrer">makeTranslation<ExternalLinkIcon/></a> ( x : Float, y : Float ) : this</h3>
<p>x - 沿X轴移动距离。
y - 沿Y轴移动距离。
将这个矩阵设置为2维平移矩阵:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> x<span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> y<span class="token punctuation">,</span>
<span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="multiply-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#multiply-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将当前矩阵乘以矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>。</p>
<h3 id="multiplymatrices-a-matrix3-b-matrix3-this" tabindex="-1"><a class="header-anchor" href="#multiplymatrices-a-matrix3-b-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.multiplyMatrices" target="_blank" rel="noopener noreferrer">multiplyMatrices<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>设置当前矩阵为矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> x 矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="multiplyscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#multiplyscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.multiplyScalar" target="_blank" rel="noopener noreferrer">multiplyScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>当前矩阵所有的元素乘以该缩放值<strong>s</strong></p>
<h3 id="set-n11-float-n12-float-n13-float-n21-float-n22-float-n23-float-n31-float-n32-float-n33-float-this" tabindex="-1"><a class="header-anchor" href="#set-n11-float-n12-float-n13-float-n21-float-n22-float-n23-float-n31-float-n32-float-n33-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( n11 : Float, n12 : Float, n13 : Float, n21 : Float, n22 : Float, n23 : Float, n31 : Float, n32 : Float, n33 : Float ) : this</h3>
<p>n11 - 设置第一行第一列的值。
n12 - 设置第一行第二列的值。
...
...
n32 - 设置第三行第二列的值。
n33 - 设置第三行第三列的值。</p>
<p>使用行优先 <a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order" target="_blank" rel="noopener noreferrer">row-major<ExternalLinkIcon/></a> 的格式来设置该矩阵。</p>
<h3 id="premultiply-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#premultiply-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.premultiply" target="_blank" rel="noopener noreferrer">premultiply<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>乘以当前矩阵。</p>
<h3 id="setfrommatrix4-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrix4-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.setFromMatrix4" target="_blank" rel="noopener noreferrer">setFromMatrix4<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>根据参数 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a> 左上 3x3 的矩阵值，设置当前矩阵的值。</p>
<h3 id="setuvtransform-tx-float-ty-float-sx-float-sy-float-rotation-float-cx-float-cy-float-this" tabindex="-1"><a class="header-anchor" href="#setuvtransform-tx-float-ty-float-sx-float-sy-float-rotation-float-cx-float-cy-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.setUvTransform" target="_blank" rel="noopener noreferrer">setUvTransform<ExternalLinkIcon/></a> ( tx : Float, ty : Float, sx : Float, sy : Float, rotation : Float, cx : Float, cy : Float ) : this</h3>
<p>tx - x偏移量
ty - y偏移量
sx - x方向的重复比例
sy - y方向的重复比例
rotation - 旋转, 弧度。Positive values rotate counterclockwise
cx - 旋转中心x
cy - 旋转中心y</p>
<p>使用偏移，重复，旋转和中心点位置设置UV变换矩阵。</p>
<h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - (可选参数) 存储矩阵元素的数组，如果未指定会创建一个新的数组。
offset - (可选参数) 存放矩阵元素数组的偏移量。</p>
<p>使用列优先<a href="https://en.wikipedia.org/wiki/Row-_and_column-major_order#Column-major_order" target="_blank" rel="noopener noreferrer">column-major<ExternalLinkIcon/></a>格式将此矩阵的元素写入数组中。</p>
<h3 id="transpose-this" tabindex="-1"><a class="header-anchor" href="#transpose-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.transpose" target="_blank" rel="noopener noreferrer">transpose<ExternalLinkIcon/></a> () : this</h3>
<p>将该矩阵转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">Transposes<ExternalLinkIcon/></a>。</p>
<h3 id="transposeintoarray-array-array-this" tabindex="-1"><a class="header-anchor" href="#transposeintoarray-array-array-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3.transposeIntoArray" target="_blank" rel="noopener noreferrer">transposeIntoArray<ExternalLinkIcon/></a> ( array : Array ) : this</h3>
<p>array - 用于存储当前矩阵转置结果的数组。</p>
<p>将当前矩阵的转置<a href="https://en.wikipedia.org/wiki/Transpose" target="_blank" rel="noopener noreferrer">Transposes<ExternalLinkIcon/></a>存入给定的数组 array 中，但不改变当前矩阵， 并返回当前矩阵。</p>
</div></template>


