<template><div><h1 id="四元数-quaternion" tabindex="-1"><a class="header-anchor" href="#四元数-quaternion" aria-hidden="true">#</a> 四元数（Quaternion）</h1>
<p>该类实现了 <a href="http://en.wikipedia.org/wiki/Quaternion" target="_blank" rel="noopener noreferrer">quaternion<ExternalLinkIcon/></a> 。
四元数在three.js中用于表示 <a href="https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation" target="_blank" rel="noopener noreferrer">rotation<ExternalLinkIcon/></a> （旋转）。</p>
<p>对 Quaternion 实例进行遍历将按相应的顺序生成它的分量 (x, y, z, w)。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> quaternion <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Quaternion</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
quaternion<span class="token punctuation">.</span><span class="token function">setFromAxisAngle</span><span class="token punctuation">(</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span> <span class="token punctuation">)</span><span class="token punctuation">,</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span> <span class="token operator">/</span> <span class="token number">2</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> 
<span class="token keyword">const</span> vector <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> vector<span class="token punctuation">.</span><span class="token function">applyQuaternion</span><span class="token punctuation">(</span> quaternion <span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="quaternion-x-float-y-float-z-float-w-float" tabindex="-1"><a class="header-anchor" href="#quaternion-x-float-y-float-z-float-w-float" aria-hidden="true">#</a> Quaternion( x : Float, y : Float, z : Float, w : Float )</h3>
<p>x - x 坐标
y - y 坐标
z - z 坐标
w - w 坐标</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="isquaternion-boolean" tabindex="-1"><a class="header-anchor" href="#isquaternion-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.isQuaternion" target="_blank" rel="noopener noreferrer">isQuaternion<ExternalLinkIcon/></a> : Boolean</h3>
<p>Read-only flag to check if a given object is of type Quaternion.</p>
<h3 id="x-float" tabindex="-1"><a class="header-anchor" href="#x-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> : Float</h3>
<h3 id="y-float" tabindex="-1"><a class="header-anchor" href="#y-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> : Float</h3>
<h3 id="z-float" tabindex="-1"><a class="header-anchor" href="#z-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> : Float</h3>
<h3 id="w-float" tabindex="-1"><a class="header-anchor" href="#w-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> : Float</h3>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="angleto-q-quaternion-float" tabindex="-1"><a class="header-anchor" href="#angleto-q-quaternion-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.angleTo" target="_blank" rel="noopener noreferrer">angleTo<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : Float</h3>
<p>以弧度返回该四元数与四元数 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> 之间的夹角。</p>
<h3 id="clone-quaternion" tabindex="-1"><a class="header-anchor" href="#clone-quaternion" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a></h3>
<p>创建一个与该四元数具有相同<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> 属性的四元数。</p>
<h3 id="conjugate-this" tabindex="-1"><a class="header-anchor" href="#conjugate-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.conjugate" target="_blank" rel="noopener noreferrer">conjugate<ExternalLinkIcon/></a> () : this</h3>
<p>返回该四元数的旋转共轭。 四元数的共轭表示的是，围绕旋转轴在相反方向上的相同旋转。</p>
<h3 id="copy-q-quaternion-this" tabindex="-1"><a class="header-anchor" href="#copy-q-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>复制四元数 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> 的 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> 属性到该四元数中。</p>
<h3 id="equals-v-quaternion-boolean" tabindex="-1"><a class="header-anchor" href="#equals-v-quaternion-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> - 用于进行比较的四元数。</p>
<p>将四元数 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> 的 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> 的属性 与当前四元数的对应属性相比较，以确定它们是否表示相同的旋转。</p>
<h3 id="dot-v-quaternion-float" tabindex="-1"><a class="header-anchor" href="#dot-v-quaternion-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.dot" target="_blank" rel="noopener noreferrer">dot<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算四元数 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> 与当前四元数的<a href="https://en.wikipedia.org/wiki/Dot_product" target="_blank" rel="noopener noreferrer">dot product<ExternalLinkIcon/></a>（点积）。</p>
<h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 用于构造四元数的形如(x, y, z, w)的数组。
offset - （可选）数组的偏移量。（译者注：使用数组中从第offset元素算起的四个元素）</p>
<p>从一个数组来设置四元数的 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a> 的属性。</p>
<h3 id="identity-this" tabindex="-1"><a class="header-anchor" href="#identity-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.identity" target="_blank" rel="noopener noreferrer">identity<ExternalLinkIcon/></a> () : this</h3>
<p>设置该四元数为 identity 四元数，即表示“不旋转”的四元数。</p>
<h3 id="invert-this" tabindex="-1"><a class="header-anchor" href="#invert-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.invert" target="_blank" rel="noopener noreferrer">invert<ExternalLinkIcon/></a> () : this</h3>
<p>翻转该四元数 —— 计算 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.conjugate" target="_blank" rel="noopener noreferrer">conjugate<ExternalLinkIcon/></a> 。假定该四元数具有单位长度。</p>
<h3 id="length-float" tabindex="-1"><a class="header-anchor" href="#length-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a> () : Float</h3>
<p>计算四元数的 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a> （欧几里得长度，直线长度），视为一个四维向量。</p>
<h3 id="lengthsq-float" tabindex="-1"><a class="header-anchor" href="#lengthsq-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.lengthSq" target="_blank" rel="noopener noreferrer">lengthSq<ExternalLinkIcon/></a> () : Float</h3>
<p>计算四元数 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a> （欧几里得长度，直线长度）的平方，视为一个四维向量。 如果要比较两个四元数的长度，这可能会十分有用， 因为这比 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>() 的效率稍高一些。</p>
<h3 id="normalize-this" tabindex="-1"><a class="header-anchor" href="#normalize-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.normalize" target="_blank" rel="noopener noreferrer">normalize<ExternalLinkIcon/></a> () : this</h3>
<p><a href="https://en.wikipedia.org/wiki/Normalized_vector" target="_blank" rel="noopener noreferrer">Normalizes<ExternalLinkIcon/></a>（归一化）四元数 —— 即计算与该四元数具有相同旋转、但长度为<strong>1</strong>的四元数。</p>
<h3 id="multiply-q-quaternion-this" tabindex="-1"><a class="header-anchor" href="#multiply-q-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>将该四元数与<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a>相乘。</p>
<h3 id="multiplyquaternions-a-quaternion-b-quaternion-this" tabindex="-1"><a class="header-anchor" href="#multiplyquaternions-a-quaternion-b-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.multiplyQuaternions" target="_blank" rel="noopener noreferrer">multiplyQuaternions<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>将该四元数设为 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> x <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a> 。
改编自 <a href="http://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/code/index.htm" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a> 所概述的方法。</p>
<h3 id="premultiply-q-quaternion-this" tabindex="-1"><a class="header-anchor" href="#premultiply-q-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.premultiply" target="_blank" rel="noopener noreferrer">premultiply<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>使用 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> 乘以该四元数。</p>
<h3 id="rotatetowards-q-quaternion-step-float-this" tabindex="-1"><a class="header-anchor" href="#rotatetowards-q-quaternion-step-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.rotateTowards" target="_blank" rel="noopener noreferrer">rotateTowards<ExternalLinkIcon/></a> ( q : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, step : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">q<ExternalLinkIcon/></a> - 目标四元数
step - 以弧度为单位的角度步长</p>
<p>将该四元数按照步长 step 向目标 <strong>q</strong> 进行旋转。该方法确保最终的四元数不会超过 <strong>q</strong>。</p>
<h3 id="slerp-qb-quaternion-t-float-this" tabindex="-1"><a class="header-anchor" href="#slerp-qb-quaternion-t-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.slerp" target="_blank" rel="noopener noreferrer">slerp<ExternalLinkIcon/></a> ( qb : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, t : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">qb<ExternalLinkIcon/></a> - 另一个四元数旋转
t - 闭区间 [0, 1] 中的插值因子</p>
<p>处理四元数之间的球面线性插值。t 表示该四元数(其中 t 为 0) 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">qb<ExternalLinkIcon/></a> (其中 t 为1) 之间的旋转量。 该四元数会被设置为上述计算的结果。另请参阅下面 <strong>slerp</strong> 的静态版本。<code v-pre>// rotate a mesh towards a target quaternion mesh.quaternion.slerp( endQuaternion, 0.01 );</code></p>
<h3 id="slerpquaternions-qa-quaternion-qb-quaternion-t-float-this" tabindex="-1"><a class="header-anchor" href="#slerpquaternions-qa-quaternion-qb-quaternion-t-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.slerpQuaternions" target="_blank" rel="noopener noreferrer">slerpQuaternions<ExternalLinkIcon/></a> ( qa : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, qb : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>, t : Float ) : this</h3>
<p>在给定的四元数之间执行球面线性插值，并将结果存储在这个四元数中</p>
<h3 id="set-x-float-y-float-z-float-w-float-this" tabindex="-1"><a class="header-anchor" href="#set-x-float-y-float-z-float-w-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float, w : Float ) : this</h3>
<p>设置该四元数的 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>属性。</p>
<h3 id="setfromaxisangle-axis-vector3-angle-float-this" tabindex="-1"><a class="header-anchor" href="#setfromaxisangle-axis-vector3-angle-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.setFromAxisAngle" target="_blank" rel="noopener noreferrer">setFromAxisAngle<ExternalLinkIcon/></a> ( axis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, angle : Float ) : this</h3>
<p>从由 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">axis<ExternalLinkIcon/></a>（轴） 和 angle（角度）所给定的旋转来设置该四元数。
改编自 <a href="http://www.euclideanspace.com/maths/geometry/rotations/conversions/angleToQuaternion/index.htm" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a> 所述的方法。
假定<strong>Axis</strong>已被归一化，<strong>angle</strong>以弧度来表示。</p>
<h3 id="setfromeuler-euler-euler-this" tabindex="-1"><a class="header-anchor" href="#setfromeuler-euler-euler-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.setFromEuler" target="_blank" rel="noopener noreferrer">setFromEuler<ExternalLinkIcon/></a> ( euler : <a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a> ) : this</h3>
<p>从由 <a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a> 角所给定的旋转来设置该四元数。</p>
<h3 id="setfromrotationmatrix-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#setfromrotationmatrix-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.setFromRotationMatrix" target="_blank" rel="noopener noreferrer">setFromRotationMatrix<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>从<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的旋转分量中来设置该四元数。
改编自 <a href="http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/index.htm" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a> 所概述的方法。</p>
<h3 id="setfromunitvectors-vfrom-vector3-vto-vector3-this" tabindex="-1"><a class="header-anchor" href="#setfromunitvectors-vfrom-vector3-vto-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.setFromUnitVectors" target="_blank" rel="noopener noreferrer">setFromUnitVectors<ExternalLinkIcon/></a> ( vFrom : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, vTo : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该四元数设置为从方向向量 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vFrom<ExternalLinkIcon/></a> 旋转到方向向量 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vTo<ExternalLinkIcon/></a> 所需的旋转。
改编自方法 <a href="http://lolengine.net/blog/2013/09/18/beautiful-maths-quaternion-from-vectors" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>。
假设 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vFrom<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">vTo<ExternalLinkIcon/></a> 都已归一化。</p>
<h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - （可选）存储该四元数的数组。若未指定该参数，则将创建一个新数组。
offset - （可选）若指定了该值，结果将会被拷贝到该 Array。</p>
<p>在形如[x, y, z, w]的数组中，返回四元数中的数字元素。</p>
<h3 id="frombufferattribute-attribute-bufferattribute-index-integer-this" tabindex="-1"><a class="header-anchor" href="#frombufferattribute-attribute-bufferattribute-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.fromBufferAttribute" target="_blank" rel="noopener noreferrer">fromBufferAttribute<ExternalLinkIcon/></a> ( attribute : <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">BufferAttribute<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> - 源 attribute。
index - attribute 中的索引。</p>
<p>从 <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> 中设置该四元数的<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>、 <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.w" target="_blank" rel="noopener noreferrer">w<ExternalLinkIcon/></a>属性。</p>
<h2 id="静态方法" tabindex="-1"><a class="header-anchor" href="#静态方法" aria-hidden="true">#</a> 静态方法</h2>
<h3 id="slerpflat-dst-array-dstoffset-integer-src0-array-srcoffset0-integer-src1-array-srcoffset1-integer-t-float-undefined" tabindex="-1"><a class="header-anchor" href="#slerpflat-dst-array-dstoffset-integer-src0-array-srcoffset0-integer-src1-array-srcoffset1-integer-t-float-undefined" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.slerpFlat" target="_blank" rel="noopener noreferrer">slerpFlat<ExternalLinkIcon/></a> ( dst : Array, dstOffset : Integer, src0 : Array, srcOffset0 : Integer, src1 : Array, srcOffset1 : Integer, t : Float ) : undefined</h3>
<p>dst - 输出数组
dstOffset - 输出数组的偏移量
src0 - 起始四元数的源数组
srcOffset0 - 数组 <strong>src0</strong> 的偏移量
src1 - 目标四元数的源数组
srcOffset1 - 数组 <strong>src1</strong> 的偏移量
t - 归一化插值因子(介于 0 和 1 之间)</p>
<p>This SLERP implementation assumes the quaternion data are managed in flat arrays.</p>
<h3 id="multiplyquaternionsflat-dst-array-dstoffset-integer-src0-array-srcoffset0-integer-src1-array-srcoffset1-integer-array" tabindex="-1"><a class="header-anchor" href="#multiplyquaternionsflat-dst-array-dstoffset-integer-src0-array-srcoffset0-integer-src1-array-srcoffset1-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion.multiplyQuaternionsFlat" target="_blank" rel="noopener noreferrer">multiplyQuaternionsFlat<ExternalLinkIcon/></a> ( dst : Array, dstOffset : Integer, src0 : Array, srcOffset0 : Integer, src1 : Array, srcOffset1 : Integer ) : Array</h3>
<p>dst - The output array.
dstOffset - An offset into the output array.
src0 - The source array of the starting quaternion.
srcOffset0 - An offset into the array <strong>src0</strong>.
src1 - The source array of the target quaternion.
srcOffset1 - An offset into the array <strong>src1</strong>.</p>
<p>This multiplication implementation assumes the quaternion data are managed in flat arrays.</p>
</div></template>


