<template><div><h1 id="射线-ray" tabindex="-1"><a class="header-anchor" href="#射线-ray" aria-hidden="true">#</a> 射线（Ray）</h1>
<p>射线由一个原点向一个确定的方向发射。它被<a href="https://threejs.org/docs/index.html#api/zh/core/Raycaster" target="_blank" rel="noopener noreferrer">Raycaster<ExternalLinkIcon/></a>（光线投射）所使用， 以用于辅助<a href="https://en.wikipedia.org/wiki/Ray_casting" target="_blank" rel="noopener noreferrer">raycasting<ExternalLinkIcon/></a>。 光线投射用于在各个物体之间进行拾取（当鼠标经过三维空间中的物体/对象时进行拾取）。</p>
<h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="ray-origin-vector3-direction-vector3" tabindex="-1"><a class="header-anchor" href="#ray-origin-vector3-direction-vector3" aria-hidden="true">#</a> Ray( origin : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, direction : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> )</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a> - （可选）<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的原点，默认值是一个位于(0, 0, 0)的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的方向。该向量必须经过标准化（使用<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.normalize" target="_blank" rel="noopener noreferrer">Vector3.normalize<ExternalLinkIcon/></a>），这样才能使方法正常运行。 默认值是一个位于(0, 0, -1)的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>创建一个新的Ray。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="origin-vector3" tabindex="-1"><a class="header-anchor" href="#origin-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的原点，默认值是一个位于(0, 0, 0)的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<h3 id="direction-vector3" tabindex="-1"><a class="header-anchor" href="#direction-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的方向。该向量必须经过标准化（使用<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.normalize" target="_blank" rel="noopener noreferrer">Vector3.normalize<ExternalLinkIcon/></a>），这样才能使方法正常运行。 默认值是一个位于(0, 0, -1)的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="applymatrix4-matrix4-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-matrix4-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( matrix4 : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">matrix4<ExternalLinkIcon/></a> - 将被用于这个<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>的<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>。</p>
<p>使用传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>来变换这个<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>。</p>
<h3 id="at-t-float-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#at-t-float-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.at" target="_blank" rel="noopener noreferrer">at<ExternalLinkIcon/></a> ( t : Float, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p>t - 使用这一传入的距离，在<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>上确定一个位置。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将复制到这一Vector3中。</p>
<p>获得这一<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>上给定距离处的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<h3 id="clone-ray" tabindex="-1"><a class="header-anchor" href="#clone-ray" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a></h3>
<p>创建一个新的和这个Ray具有相同<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a>的Ray。</p>
<h3 id="closestpointtopoint-point-vector3-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#closestpointtopoint-point-vector3-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.closestPointToPoint" target="_blank" rel="noopener noreferrer">closestPointToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 获得距离射线上的点最接近的点。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将复制到这一Vector3中。</p>
<p>沿着<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>，获得与所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>最接近的点。</p>
<h3 id="copy-ray-ray-this" tabindex="-1"><a class="header-anchor" href="#copy-ray-ray-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( ray : <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a> ) : this</h3>
<p>复制所传入Ray的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a>属性到这个Ray上。</p>
<h3 id="distancesqtopoint-point-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancesqtopoint-point-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.distanceSqToPoint" target="_blank" rel="noopener noreferrer">distanceSqToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - 将被用于计算到其距离的 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>获得<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>与传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>之间最近的平方距离。</p>
<h3 id="distancesqtosegment-v0-vector3-v1-vector3-optionalpointonray-vector3-optionalpointonsegment-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancesqtosegment-v0-vector3-v1-vector3-optionalpointonray-vector3-optionalpointonsegment-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.distanceSqToSegment" target="_blank" rel="noopener noreferrer">distanceSqToSegment<ExternalLinkIcon/></a> ( v0 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, v1 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, optionalPointOnRay : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, optionalPointOnSegment : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v0<ExternalLinkIcon/></a> - 线段的起点。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a> - 线段的终点。
optionalPointOnRay - （可选）若这个值被给定，它将接收在<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）上距离线段最近的点。
optionalPointOnSegment - （可选）若这个值被给定，它将接收在线段上距离<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）最近的点。</p>
<p>获取<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）与线段之间的平方距离。</p>
<h3 id="distancetoplane-plane-plane-float" tabindex="-1"><a class="header-anchor" href="#distancetoplane-plane-plane-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.distanceToPlane" target="_blank" rel="noopener noreferrer">distanceToPlane<ExternalLinkIcon/></a> ( plane : <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> - 将要获取射线原点到该平面的距离的平面。</p>
<p>获取射线原点（<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a>）到平面（<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>）之间的距离。若射线（<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>）不与平面（<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>）相交，则将返回<strong>null</strong>。</p>
<h3 id="distancetopoint-point-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancetopoint-point-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.distanceToPoint" target="_blank" rel="noopener noreferrer">distanceToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 将被用于计算到其距离的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。</p>
<p>获得<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）到所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>之间最接近的距离。</p>
<h3 id="equals-ray-ray-boolean" tabindex="-1"><a class="header-anchor" href="#equals-ray-ray-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( ray : <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">ray<ExternalLinkIcon/></a> - 用于比较的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>。</p>
<p>如果所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">ray<ExternalLinkIcon/></a>具有和当前Ray相同的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a>则返回true。</p>
<h3 id="intersectbox-box-box3-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#intersectbox-box-box3-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectBox" target="_blank" rel="noopener noreferrer">intersectBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将会与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会被复制到这一Vector3中。</p>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）与一个<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>相交，并返回交点，倘若没有交点将返回<strong>null</strong>。</p>
<h3 id="intersectplane-plane-plane-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#intersectplane-plane-plane-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectPlane" target="_blank" rel="noopener noreferrer">intersectPlane<ExternalLinkIcon/></a> ( plane : <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> - 将会与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会被复制到这一Vector3中。</p>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）与一个<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>相交，并返回交点，倘若没有交点将返回<strong>null</strong>。</p>
<h3 id="intersectsphere-sphere-sphere-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#intersectsphere-sphere-sphere-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectSphere" target="_blank" rel="noopener noreferrer">intersectSphere<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> - 将会与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会被复制到这一Vector3中。</p>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）与一个<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>（球）相交，并返回交点，倘若没有交点将返回<strong>null</strong>。</p>
<h3 id="intersecttriangle-a-vector3-b-vector3-c-vector3-backfaceculling-boolean-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#intersecttriangle-a-vector3-b-vector3-c-vector3-backfaceculling-boolean-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectTriangle" target="_blank" rel="noopener noreferrer">intersectTriangle<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, c : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, backfaceCulling : Boolean, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a>, <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>, <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">c<ExternalLinkIcon/></a> - 组成三角形的三个<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
backfaceCulling - 是否使用背面剔除。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将会被复制到这一Vector3中。</p>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）与一个三角形相交，并返回交点，倘若没有交点将返回<strong>null</strong>。</p>
<h3 id="intersectsbox-box-box3-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsbox-box-box3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectsBox" target="_blank" rel="noopener noreferrer">intersectsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将被检查是否与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>。</p>
<p>若这一射线与<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>相交，则将返回true。</p>
<h3 id="intersectsplane-plane-plane-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsplane-plane-plane-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectsPlane" target="_blank" rel="noopener noreferrer">intersectsPlane<ExternalLinkIcon/></a> ( plane : <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> - 将被检查是否与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>。</p>
<p>若这一射线与<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a>相交，则将返回true。</p>
<h3 id="intersectssphere-sphere-sphere-boolean" tabindex="-1"><a class="header-anchor" href="#intersectssphere-sphere-sphere-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.intersectsSphere" target="_blank" rel="noopener noreferrer">intersectsSphere<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> - 将被检查是否与之相交的<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>。</p>
<p>若这一射线与<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a>相交，则将返回true。</p>
<h3 id="lookat-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#lookat-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.lookAt" target="_blank" rel="noopener noreferrer">lookAt<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> - 将要“直视”的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></p>
<p>调整光线的方向到世界坐标中该向量所指代的点。</p>
<h3 id="recast-t-float-this" tabindex="-1"><a class="header-anchor" href="#recast-t-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.recast" target="_blank" rel="noopener noreferrer">recast<ExternalLinkIcon/></a> ( t : Float ) : this</h3>
<p>t - 沿着<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>进行插值的距离。</p>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的原点沿着其方向移动给定的距离。</p>
<h3 id="set-origin-vector3-direction-vector3-this" tabindex="-1"><a class="header-anchor" href="#set-origin-vector3-direction-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( origin : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, direction : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a>（原点）。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Ray" target="_blank" rel="noopener noreferrer">Ray<ExternalLinkIcon/></a>（射线）的<a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a>（方向）。 该向量必须经过标准化（使用<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.normalize" target="_blank" rel="noopener noreferrer">Vector3.normalize<ExternalLinkIcon/></a>），这样才能使方法正常运行。</p>
<p>根据参数设置该射线的 <a href="https://threejs.org/docs/index.html#api/zh/math/Ray.origin" target="_blank" rel="noopener noreferrer">origin<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Ray.direction" target="_blank" rel="noopener noreferrer">direction<ExternalLinkIcon/></a> 。</p>
</div></template>


