<template><div><h1 id="球-sphere" tabindex="-1"><a class="header-anchor" href="#球-sphere" aria-hidden="true">#</a> 球（Sphere）</h1>
<p>一个球由球心和半径所定义。</p>
<h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="sphere-center-vector3-radius-float" tabindex="-1"><a class="header-anchor" href="#sphere-center-vector3-radius-float" aria-hidden="true">#</a> Sphere( center : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, radius : Float )</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> - 球心的位置，默认值是一个位于(0, 0, 0)的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
radius - 球的半径，默认值是-1。</p>
<p>创建一个新的Sphere。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="center-vector3" tabindex="-1"><a class="header-anchor" href="#center-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.center" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p>A <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>定义了球心的位置，默认值位于(0, 0, 0)。</p>
<h3 id="radius-float" tabindex="-1"><a class="header-anchor" href="#radius-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a> : Float</h3>
<p>球的半径，默认值为-1。</p>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="applymatrix4-matrix-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-matrix-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( matrix : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a> - 将被应用的<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>矩阵。</p>
<p>使用所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>矩阵来对球进行变换。</p>
<h3 id="clamppoint-point-vector3-target-vector3-vector3" tabindex="-1"><a class="header-anchor" href="#clamppoint-point-vector3-target-vector3-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.clampPoint" target="_blank" rel="noopener noreferrer">clampPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, target : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 将要夹取的点。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将被复制到这个Vector3中。</p>
<p>从球中夹取一个点。若这一点位于球外，则将会夹取到该点球边缘最近的点。已位于球中的点将不会受到影响。</p>
<h3 id="clone-sphere" tabindex="-1"><a class="header-anchor" href="#clone-sphere" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a></h3>
<p>返回一个新的球，新的球与这个球具有相同的<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.center" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>。</p>
<h3 id="containspoint-point-vector3-boolean" tabindex="-1"><a class="header-anchor" href="#containspoint-point-vector3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.containsPoint" target="_blank" rel="noopener noreferrer">containsPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 要被检查的点</p>
<p>检查球体中是否包含所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>点，包括球的表面。</p>
<h3 id="copy-sphere-sphere-this" tabindex="-1"><a class="header-anchor" href="#copy-sphere-sphere-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : this</h3>
<p>复制所传入的球的<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.center" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>到这个球上。</p>
<h3 id="distancetopoint-point-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancetopoint-point-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.distanceToPoint" target="_blank" rel="noopener noreferrer">distanceToPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>返回球的边界到所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>点的最近距离。 若这个点位于球内，则距离将为负值。</p>
<h3 id="expandbypoint-point-vector3-this" tabindex="-1"><a class="header-anchor" href="#expandbypoint-point-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.expandByPoint" target="_blank" rel="noopener noreferrer">expandByPoint<ExternalLinkIcon/></a> ( point : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 将被包含在球内的点</p>
<p>扩展该球的边界以包含此点 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">point<ExternalLinkIcon/></a>。</p>
<h3 id="isempty-boolean" tabindex="-1"><a class="header-anchor" href="#isempty-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.isEmpty" target="_blank" rel="noopener noreferrer">isEmpty<ExternalLinkIcon/></a> () : Boolean</h3>
<p>检查球是否为空(球半径为负值)。半径为 0 的球体仅包含其中心点，并不会被视为空。</p>
<h3 id="makeempty-this" tabindex="-1"><a class="header-anchor" href="#makeempty-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.makeEmpty" target="_blank" rel="noopener noreferrer">makeEmpty<ExternalLinkIcon/></a> () : this</h3>
<p>将该球修改为空，即中心点 <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.center" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> 为 (0,0,0)，半径 <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a> 为 -1。</p>
<h3 id="equals-sphere-sphere-boolean" tabindex="-1"><a class="header-anchor" href="#equals-sphere-sphere-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>检查这两个球的球心与半径是否相等。</p>
<h3 id="getboundingbox-target-box3-box3" tabindex="-1"><a class="header-anchor" href="#getboundingbox-target-box3-box3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.getBoundingBox" target="_blank" rel="noopener noreferrer">getBoundingBox<ExternalLinkIcon/></a> ( target : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a></h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">target<ExternalLinkIcon/></a> — 结果将被复制到这个Box3中。</p>
<p>返回这个球的<a href="https://en.wikipedia.org/wiki/Minimum_bounding_box" target="_blank" rel="noopener noreferrer">Minimum Bounding Box<ExternalLinkIcon/></a>（最小包围盒）。</p>
<h3 id="intersectsbox-box-box3-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsbox-box-box3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.intersectsBox" target="_blank" rel="noopener noreferrer">intersectsBox<ExternalLinkIcon/></a> ( box : <a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a> - 将被用于测试是否与这个球有交集的<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">Box3<ExternalLinkIcon/></a>。</p>
<p>检测这个球与所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Box3" target="_blank" rel="noopener noreferrer">box<ExternalLinkIcon/></a>是否有交集。</p>
<h3 id="intersectsplane-plane-plane-boolean" tabindex="-1"><a class="header-anchor" href="#intersectsplane-plane-plane-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.intersectsPlane" target="_blank" rel="noopener noreferrer">intersectsPlane<ExternalLinkIcon/></a> ( plane : <a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">Plane<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a> - 将被用于测试是否与这个球有交集的Plane。</p>
<p>检测这个球与所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Plane" target="_blank" rel="noopener noreferrer">plane<ExternalLinkIcon/></a>是否有交集。</p>
<h3 id="intersectssphere-sphere-sphere-boolean" tabindex="-1"><a class="header-anchor" href="#intersectssphere-sphere-sphere-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.intersectsSphere" target="_blank" rel="noopener noreferrer">intersectsSphere<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : Boolean</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> - 将被用于测试是否与这个球有交集的Sphere。</p>
<p>检测两球之间是否有交集。</p>
<h3 id="set-center-vector3-radius-float-this" tabindex="-1"><a class="header-anchor" href="#set-center-vector3-radius-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( center : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, radius : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> - 球心位置。
radius - 球的半径。</p>
<p>设置球的<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.center" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.radius" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>属性。
请注意此，方法使用复制的方式来设置中心值。</p>
<h3 id="setfrompoints-points-array-optionalcenter-vector3-this" tabindex="-1"><a class="header-anchor" href="#setfrompoints-points-array-optionalcenter-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.setFromPoints" target="_blank" rel="noopener noreferrer">setFromPoints<ExternalLinkIcon/></a> ( points : Array, optionalCenter : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>points - 一个包含有<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>位置的Array。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">optionalCenter<ExternalLinkIcon/></a> - 可选， <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> 球心位置。</p>
<p>计算一个points数组（中的点）的最小边界球。如果给定了<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">optionalCenter<ExternalLinkIcon/></a>，则它将被用作该球的球心； 否则，环绕points的包围盒的轴心将通过计算来得到。</p>
<h3 id="translate-offset-vector3-this" tabindex="-1"><a class="header-anchor" href="#translate-offset-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.translate" target="_blank" rel="noopener noreferrer">translate<ExternalLinkIcon/></a> ( offset : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>使用所给定<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> offset（偏移量）平移球心。</p>
<h3 id="union-sphere-sphere-this" tabindex="-1"><a class="header-anchor" href="#union-sphere-sphere-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Sphere.union" target="_blank" rel="noopener noreferrer">union<ExternalLinkIcon/></a> ( sphere : <a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">Sphere<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Sphere" target="_blank" rel="noopener noreferrer">sphere<ExternalLinkIcon/></a> - 将与该球体即将结合的边界球体。</p>
<p>扩展此球体以包含原始球体和给定球体。</p>
</div></template>


