<template><div><h1 id="三维向量-vector3" tabindex="-1"><a class="header-anchor" href="#三维向量-vector3" aria-hidden="true">#</a> 三维向量（Vector3）</h1>
<p>该类表示的是一个三维向量（3D <a href="https://en.wikipedia.org/wiki/Vector_space" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a>）。 一个三维向量表示的是一个有顺序的、三个为一组的数字组合（标记为x、y和z）， 可被用来表示很多事物，例如：</p>
<ul>
<li>一个位于三维空间中的点。</li>
<li>一个在三维空间中的方向与长度的定义。在three.js中，长度总是从(0, 0, 0)到(x, y, z)的 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a>（欧几里德距离，即直线距离）， 方向也是从(0, 0, 0)到(x, y, z)的方向。</li>
<li>任意的、有顺序的、三个为一组的数字组合。</li>
</ul>
<p>其他的一些事物也可以使用二维向量进行表示，比如说动量矢量等等； 但以上这些是它在three.js中的常用用途。</p>
<p>对 Vector3 实例进行遍历将按相应的顺序生成它的分量 (x, y, z)。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> a <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Vector3</span><span class="token punctuation">(</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//no arguments; will be initialised to (0, 0, 0) const b = new THREE.Vector3( ); const d = a.distanceTo( b );</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="vector3-x-float-y-float-z-float" tabindex="-1"><a class="header-anchor" href="#vector3-x-float-y-float-z-float" aria-hidden="true">#</a> Vector3( x : Float, y : Float, z : Float )</h3>
<p>x - 向量的x值，默认为<strong>0</strong>。
y - 向量的y值，默认为<strong>0</strong>。
z - 向量的z值，默认为<strong>0</strong>。</p>
<p>创建一个新的Vector3。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="isvector3-boolean" tabindex="-1"><a class="header-anchor" href="#isvector3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.isVector3" target="_blank" rel="noopener noreferrer">isVector3<ExternalLinkIcon/></a> : Boolean</h3>
<p>Read-only flag to check if a given object is of type Vector3.</p>
<h3 id="x-float" tabindex="-1"><a class="header-anchor" href="#x-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> : Float</h3>
<h3 id="y-float" tabindex="-1"><a class="header-anchor" href="#y-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> : Float</h3>
<h3 id="z-float" tabindex="-1"><a class="header-anchor" href="#z-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> : Float</h3>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="add-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#add-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.add" target="_blank" rel="noopener noreferrer">add<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>和这个向量相加。</p>
<h3 id="addscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.addScalar" target="_blank" rel="noopener noreferrer">addScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将传入的标量s和这个向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值相加。</p>
<h3 id="addscaledvector-v-vector3-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscaledvector-v-vector3-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.addScaledVector" target="_blank" rel="noopener noreferrer">addScaledVector<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, s : Float ) : this</h3>
<p>将所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>与s相乘所得的乘积和这个向量相加。</p>
<h3 id="addvectors-a-vector3-b-vector3-this" tabindex="-1"><a class="header-anchor" href="#addvectors-a-vector3-b-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.addVectors" target="_blank" rel="noopener noreferrer">addVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> + <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="applyaxisangle-axis-vector3-angle-float-this" tabindex="-1"><a class="header-anchor" href="#applyaxisangle-axis-vector3-angle-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyAxisAngle" target="_blank" rel="noopener noreferrer">applyAxisAngle<ExternalLinkIcon/></a> ( axis : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, angle : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">axis<ExternalLinkIcon/></a> - 一个被归一化的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
angle - 以弧度表示的角度。</p>
<p>将轴和角度所指定的旋转应用到该向量上。</p>
<h3 id="applyeuler-euler-euler-this" tabindex="-1"><a class="header-anchor" href="#applyeuler-euler-euler-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyEuler" target="_blank" rel="noopener noreferrer">applyEuler<ExternalLinkIcon/></a> ( euler : <a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a> ) : this</h3>
<p>通过将<a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a>（欧拉）对象转换为<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>（四元数）并应用， 将欧拉变换应用到这一向量上。</p>
<h3 id="applymatrix3-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#applymatrix3-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyMatrix3" target="_blank" rel="noopener noreferrer">applyMatrix3<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量乘以三阶矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>。</p>
<h3 id="applymatrix4-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#applymatrix4-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyMatrix4" target="_blank" rel="noopener noreferrer">applyMatrix4<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量乘以四阶矩阵m（第四个维度隐式地为1），并按角度进行划分。</p>
<h3 id="applynormalmatrix-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#applynormalmatrix-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyNormalMatrix" target="_blank" rel="noopener noreferrer">applyNormalMatrix<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量乘以正规矩阵 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>，并将结果进行归一化。</p>
<h3 id="applyquaternion-quaternion-quaternion-this" tabindex="-1"><a class="header-anchor" href="#applyquaternion-quaternion-quaternion-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.applyQuaternion" target="_blank" rel="noopener noreferrer">applyQuaternion<ExternalLinkIcon/></a> ( quaternion : <a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a> ) : this</h3>
<p>将<a href="https://threejs.org/docs/index.html#api/zh/math/Quaternion" target="_blank" rel="noopener noreferrer">Quaternion<ExternalLinkIcon/></a>变换应用到该向量。</p>
<h3 id="angleto-v-vector3-float" tabindex="-1"><a class="header-anchor" href="#angleto-v-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.angleTo" target="_blank" rel="noopener noreferrer">angleTo<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>以弧度返回该向量与向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>之间的角度。</p>
<h3 id="ceil-this" tabindex="-1"><a class="header-anchor" href="#ceil-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.ceil" target="_blank" rel="noopener noreferrer">ceil<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>分量、 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量以及<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>分量向上取整为最接近的整数。</p>
<h3 id="clamp-min-vector3-max-vector3-this" tabindex="-1"><a class="header-anchor" href="#clamp-min-vector3-max-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.clamp" target="_blank" rel="noopener noreferrer">clamp<ExternalLinkIcon/></a> ( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - 在限制范围内，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>的最小值。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - 在限制范围内，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>的最大值。</p>
<p>如果该向量的x值、y值或z值大于限制范围内最大x值、y值或z值，则该值将会被所对应的值取代。</p>
<p>如果该向量的x值、y值或z值小于限制范围内最小x值、y值或z值，则该值将会被所对应的值取代。</p>
<h3 id="clamplength-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clamplength-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.clampLength" target="_blank" rel="noopener noreferrer">clampLength<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 长度将被限制为的最小值
max - 长度将被限制为的最大值</p>
<p>如果向量长度大于最大值，则它将会被最大值所取代。</p>
<p>如果向量长度小于最小值，则它将会被最小值所取代。</p>
<h3 id="clampscalar-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clampscalar-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.clampScalar" target="_blank" rel="noopener noreferrer">clampScalar<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 分量将被限制为的最小值
max - 分量将被限制为的最大值</p>
<p>如果该向量的x值、y值或z值大于最大值，则它们将被最大值所取代。</p>
<p>如果该向量的x值、y值或z值小于最小值，则它们将被最小值所取代。</p>
<h3 id="clone-vector3" tabindex="-1"><a class="header-anchor" href="#clone-vector3" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a></h3>
<p>返回一个新的Vector3，其具有和当前这个向量相同的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>。</p>
<h3 id="copy-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#copy-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将所传入Vector3的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>属性复制给这一Vector3。</p>
<h3 id="cross-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#cross-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.cross" target="_blank" rel="noopener noreferrer">cross<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为它本身与传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的叉积（<a href="https://en.wikipedia.org/wiki/Cross_product" target="_blank" rel="noopener noreferrer">cross product<ExternalLinkIcon/></a>）。</p>
<h3 id="crossvectors-a-vector3-b-vector3-this" tabindex="-1"><a class="header-anchor" href="#crossvectors-a-vector3-b-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.crossVectors" target="_blank" rel="noopener noreferrer">crossVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a>与<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>的叉积（<a href="https://en.wikipedia.org/wiki/Cross_product" target="_blank" rel="noopener noreferrer">cross product<ExternalLinkIcon/></a>）。</p>
<h3 id="distanceto-v-vector3-float" tabindex="-1"><a class="header-anchor" href="#distanceto-v-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.distanceTo" target="_blank" rel="noopener noreferrer">distanceTo<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该向量到所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>间的距离。</p>
<h3 id="manhattandistanceto-v-vector3-float" tabindex="-1"><a class="header-anchor" href="#manhattandistanceto-v-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.manhattanDistanceTo" target="_blank" rel="noopener noreferrer">manhattanDistanceTo<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该向量到所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>之间的曼哈顿距离（<a href="https://en.wikipedia.org/wiki/Taxicab_geometry" target="_blank" rel="noopener noreferrer">Manhattan distance<ExternalLinkIcon/></a>）。</p>
<h3 id="distancetosquared-v-vector3-float" tabindex="-1"><a class="header-anchor" href="#distancetosquared-v-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.distanceToSquared" target="_blank" rel="noopener noreferrer">distanceToSquared<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该向量到传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的平方距离。 如果你只是将该距离和另一个距离进行比较，则应当比较的是距离的平方， 因为它的计算效率会更高一些。</p>
<h3 id="divide-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#divide-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.divide" target="_blank" rel="noopener noreferrer">divide<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量除以向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="dividescalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#dividescalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.divideScalar" target="_blank" rel="noopener noreferrer">divideScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量除以标量s。</p>
<h3 id="dot-v-vector3-float" tabindex="-1"><a class="header-anchor" href="#dot-v-vector3-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.dot" target="_blank" rel="noopener noreferrer">dot<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector和所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的点积（<a href="https://en.wikipedia.org/wiki/Dot_product" target="_blank" rel="noopener noreferrer">dot product<ExternalLinkIcon/></a>）。</p>
<h3 id="equals-v-vector3-boolean" tabindex="-1"><a class="header-anchor" href="#equals-v-vector3-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>检查该向量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的严格相等性。</p>
<h3 id="floor-this" tabindex="-1"><a class="header-anchor" href="#floor-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.floor" target="_blank" rel="noopener noreferrer">floor<ExternalLinkIcon/></a> () : this</h3>
<p>向量的分量向下取整为最接近的整数值。</p>
<h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 来源矩阵。
offset - （可选）在数组中的元素偏移量，默认值为0。</p>
<p>设置向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值为array[ offset + 0 ]，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值为array[ offset + 1 ]， <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值为array[ offset + 2 ]。</p>
<h3 id="frombufferattribute-attribute-bufferattribute-index-integer-this" tabindex="-1"><a class="header-anchor" href="#frombufferattribute-attribute-bufferattribute-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.fromBufferAttribute" target="_blank" rel="noopener noreferrer">fromBufferAttribute<ExternalLinkIcon/></a> ( attribute : <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">BufferAttribute<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> - 来源的attribute。
index - 在attribute中的索引。</p>
<p>从<a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a>中设置向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值。</p>
<h3 id="getcomponent-index-integer-float" tabindex="-1"><a class="header-anchor" href="#getcomponent-index-integer-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.getComponent" target="_blank" rel="noopener noreferrer">getComponent<ExternalLinkIcon/></a> ( index : Integer ) : Float</h3>
<p>index - 0, 1 or 2.</p>
<p>如果index值为0返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值。
如果index值为1返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值。
如果index值为2返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值。</p>
<h3 id="length-float" tabindex="-1"><a class="header-anchor" href="#length-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0, 0) 到 (x, y, z)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）</p>
<h3 id="manhattanlength-float" tabindex="-1"><a class="header-anchor" href="#manhattanlength-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.manhattanLength" target="_blank" rel="noopener noreferrer">manhattanLength<ExternalLinkIcon/></a> () : Float</h3>
<p>计算该向量的曼哈顿长度（<a href="http://en.wikipedia.org/wiki/Taxicab_geometry" target="_blank" rel="noopener noreferrer">Manhattan length<ExternalLinkIcon/></a>）。</p>
<h3 id="lengthsq-float" tabindex="-1"><a class="header-anchor" href="#lengthsq-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.lengthSq" target="_blank" rel="noopener noreferrer">lengthSq<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0, 0)到(x, y, z)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）的平方。 如果你正在比较向量的长度，应当比较的是长度的平方，因为它的计算效率更高一些。</p>
<h3 id="lerp-v-vector3-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerp-v-vector3-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.lerp" target="_blank" rel="noopener noreferrer">lerp<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围通常在[0, 1]闭区间。</p>
<p>在该向量与传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>之间的线性插值，alpha是沿着线的长度的百分比 —— alpha = 0 时表示的是当前向量，alpha = 1 时表示的是所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="lerpvectors-v1-vector3-v2-vector3-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerpvectors-v1-vector3-v2-vector3-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.lerpVectors" target="_blank" rel="noopener noreferrer">lerpVectors<ExternalLinkIcon/></a> ( v1 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, v2 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a> - 起始的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围通常在[0, 1]闭区间。</p>
<p>将此向量设置为在<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>之间进行线性插值的向量， 其中alpha为两个向量之间连线的长度的百分比 —— alpha = 0 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>，alpha = 1 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>。</p>
<h3 id="max-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#max-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值、y值或z值小于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值、y值或z值， 则将该值替换为对应的最大值。</p>
<h3 id="min-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#min-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值、y值或z值大于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值、y值或z值， 则将该值替换为对应的最小值。</p>
<h3 id="multiply-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#multiply-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量与所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>进行相乘。</p>
<h3 id="multiplyscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#multiplyscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.multiplyScalar" target="_blank" rel="noopener noreferrer">multiplyScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量与所传入的标量s进行相乘。</p>
<h3 id="multiplyvectors-a-vector3-b-vector3-this" tabindex="-1"><a class="header-anchor" href="#multiplyvectors-a-vector3-b-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.multiplyVectors" target="_blank" rel="noopener noreferrer">multiplyVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>按照分量顺序，将该向量设置为和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> * <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>相等。</p>
<h3 id="negate-this" tabindex="-1"><a class="header-anchor" href="#negate-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.negate" target="_blank" rel="noopener noreferrer">negate<ExternalLinkIcon/></a> () : this</h3>
<p>向量取反，即： x = -x, y = -y , z = -z。</p>
<h3 id="normalize-this" tabindex="-1"><a class="header-anchor" href="#normalize-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.normalize" target="_blank" rel="noopener noreferrer">normalize<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量转换为单位向量（<a href="https://en.wikipedia.org/wiki/Unit_vector" target="_blank" rel="noopener noreferrer">unit vector<ExternalLinkIcon/></a>）， 也就是说，将该向量的方向设置为和原向量相同，但是其长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为1。</p>
<h3 id="project-camera-camera-this" tabindex="-1"><a class="header-anchor" href="#project-camera-camera-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.project" target="_blank" rel="noopener noreferrer">project<ExternalLinkIcon/></a> ( camera : <a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera" target="_blank" rel="noopener noreferrer">Camera<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera" target="_blank" rel="noopener noreferrer">camera<ExternalLinkIcon/></a> — 在投影中使用的摄像机。</p>
<p>将此向量(坐标)从世界空间投影到相机的标准化设备坐标 (NDC) 空间。</p>
<h3 id="projectonplane-planenormal-vector3-this" tabindex="-1"><a class="header-anchor" href="#projectonplane-planenormal-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.projectOnPlane" target="_blank" rel="noopener noreferrer">projectOnPlane<ExternalLinkIcon/></a> ( planeNormal : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">planeNormal<ExternalLinkIcon/></a> - 表示平面法线的向量</p>
<p><a href="https://en.wikipedia.org/wiki/Vector_projection" target="_blank" rel="noopener noreferrer">Projects<ExternalLinkIcon/></a> 通过从该向量减去投影到平面法线上的向量，将该向量投影到平面上。</p>
<h3 id="projectonvector-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#projectonvector-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.projectOnVector" target="_blank" rel="noopener noreferrer">projectOnVector<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>投影（<a href="https://en.wikipedia.org/wiki/Vector_projection" target="_blank" rel="noopener noreferrer">Projects<ExternalLinkIcon/></a>）该向量到向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>上。</p>
<h3 id="reflect-normal-vector3-this" tabindex="-1"><a class="header-anchor" href="#reflect-normal-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.reflect" target="_blank" rel="noopener noreferrer">reflect<ExternalLinkIcon/></a> ( normal : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">normal<ExternalLinkIcon/></a> - 反射面法线</p>
<p>将该向量设置为对指定 normal 法线的表面的反射向量。假设法线具有单位长度。</p>
<h3 id="round-this" tabindex="-1"><a class="header-anchor" href="#round-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.round" target="_blank" rel="noopener noreferrer">round<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的分量四舍五入取整为最接近的整数值。</p>
<h3 id="roundtozero-this" tabindex="-1"><a class="header-anchor" href="#roundtozero-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.roundToZero" target="_blank" rel="noopener noreferrer">roundToZero<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的分量朝向0取整数（若分量为负数则向上取整，若为正数则向下取整）。</p>
<h3 id="set-x-float-y-float-z-float-this" tabindex="-1"><a class="header-anchor" href="#set-x-float-y-float-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( x : Float, y : Float, z : Float ) : this</h3>
<p>设置该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> 和 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 分量。</p>
<h3 id="setcomponent-index-integer-value-float-this" tabindex="-1"><a class="header-anchor" href="#setcomponent-index-integer-value-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setComponent" target="_blank" rel="noopener noreferrer">setComponent<ExternalLinkIcon/></a> ( index : Integer, value : Float ) : this</h3>
<p>index - 0、1 或 2。
value - Float</p>
<p>若index为 0 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> 值为 value。
若index为 1 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> 值为 value。
若index为 2 则设置 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 值为 value。</p>
<h3 id="setfromcylindrical-c-cylindrical-this" tabindex="-1"><a class="header-anchor" href="#setfromcylindrical-c-cylindrical-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromCylindrical" target="_blank" rel="noopener noreferrer">setFromCylindrical<ExternalLinkIcon/></a> ( c : <a href="https://threejs.org/docs/index.html#api/zh/math/Cylindrical" target="_blank" rel="noopener noreferrer">Cylindrical<ExternalLinkIcon/></a> ) : this</h3>
<p>从圆柱坐标<a href="https://threejs.org/docs/index.html#api/zh/math/Cylindrical" target="_blank" rel="noopener noreferrer">c<ExternalLinkIcon/></a>中设置该向量。</p>
<h3 id="setfromcylindricalcoords-radius-float-theta-float-y-float-this" tabindex="-1"><a class="header-anchor" href="#setfromcylindricalcoords-radius-float-theta-float-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromCylindricalCoords" target="_blank" rel="noopener noreferrer">setFromCylindricalCoords<ExternalLinkIcon/></a> ( radius : Float, theta : Float, y : Float ) : this</h3>
<p>从圆柱坐标中的<a href="https://threejs.org/docs/index.html#api/zh/math/Cylindrical" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Cylindrical" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Cylindrical" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>设置该向量。</p>
<h3 id="setfromeuler-euler-euler-this" tabindex="-1"><a class="header-anchor" href="#setfromeuler-euler-euler-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromEuler" target="_blank" rel="noopener noreferrer">setFromEuler<ExternalLinkIcon/></a> ( euler : <a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler<ExternalLinkIcon/></a> ) : this</h3>
<p>根据指定的<a href="https://threejs.org/docs/index.html#api/zh/math/Euler" target="_blank" rel="noopener noreferrer">Euler Angle<ExternalLinkIcon/></a>的x、y、z分量来设置该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>分量。</p>
<h3 id="setfrommatrixcolumn-matrix-matrix4-index-integer-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrixcolumn-matrix-matrix4-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrixColumn" target="_blank" rel="noopener noreferrer">setFromMatrixColumn<ExternalLinkIcon/></a> ( matrix : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p>从传入的四阶矩阵<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a>由index指定的列中， 设置该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值。</p>
<h3 id="setfrommatrix3column-matrix-matrix3-index-integer-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrix3column-matrix-matrix3-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrix3Column" target="_blank" rel="noopener noreferrer">setFromMatrix3Column<ExternalLinkIcon/></a> ( matrix : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p>从传入的三阶矩阵 <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">matrix<ExternalLinkIcon/></a> 由 index 指定的列中，设置该向量的 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> 值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> 值和 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a> 值。</p>
<h3 id="setfrommatrixposition-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrixposition-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrixPosition" target="_blank" rel="noopener noreferrer">setFromMatrixPosition<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>从变换矩阵（<a href="https://en.wikipedia.org/wiki/Transformation_matrix" target="_blank" rel="noopener noreferrer">transformation matrix<ExternalLinkIcon/></a>）<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>中， 设置该向量为其中与位置相关的元素。</p>
<h3 id="setfrommatrixscale-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#setfrommatrixscale-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromMatrixScale" target="_blank" rel="noopener noreferrer">setFromMatrixScale<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>从变换矩阵（<a href="https://en.wikipedia.org/wiki/Transformation_matrix" target="_blank" rel="noopener noreferrer">transformation matrix<ExternalLinkIcon/></a>）<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>中， 设置该向量为其中与缩放相关的元素。</p>
<h3 id="setfromspherical-s-spherical-this" tabindex="-1"><a class="header-anchor" href="#setfromspherical-s-spherical-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromSpherical" target="_blank" rel="noopener noreferrer">setFromSpherical<ExternalLinkIcon/></a> ( s : <a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">Spherical<ExternalLinkIcon/></a> ) : this</h3>
<p>从球坐标<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">s<ExternalLinkIcon/></a>中设置该向量。</p>
<h3 id="setfromsphericalcoords-radius-float-phi-float-theta-float-this" tabindex="-1"><a class="header-anchor" href="#setfromsphericalcoords-radius-float-phi-float-theta-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setFromSphericalCoords" target="_blank" rel="noopener noreferrer">setFromSphericalCoords<ExternalLinkIcon/></a> ( radius : Float, phi : Float, theta : Float ) : this</h3>
<p>从球坐标中的<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">radius<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">phi<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Spherical" target="_blank" rel="noopener noreferrer">theta<ExternalLinkIcon/></a>设置该向量。</p>
<h3 id="setlength-l-float-this" tabindex="-1"><a class="header-anchor" href="#setlength-l-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setLength" target="_blank" rel="noopener noreferrer">setLength<ExternalLinkIcon/></a> ( l : Float ) : this</h3>
<p>将该向量的方向设置为和原向量相同，但是长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为l。</p>
<h3 id="setscalar-scalar-float-this" tabindex="-1"><a class="header-anchor" href="#setscalar-scalar-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setScalar" target="_blank" rel="noopener noreferrer">setScalar<ExternalLinkIcon/></a> ( scalar : Float ) : this</h3>
<p>将该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值同时设置为等于传入的scalar。</p>
<h3 id="setx-x-float-this" tabindex="-1"><a class="header-anchor" href="#setx-x-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setX" target="_blank" rel="noopener noreferrer">setX<ExternalLinkIcon/></a> ( x : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值替换为x。</p>
<h3 id="sety-y-float-this" tabindex="-1"><a class="header-anchor" href="#sety-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setY" target="_blank" rel="noopener noreferrer">setY<ExternalLinkIcon/></a> ( y : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值替换为y。</p>
<h3 id="setz-z-float-this" tabindex="-1"><a class="header-anchor" href="#setz-z-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.setZ" target="_blank" rel="noopener noreferrer">setZ<ExternalLinkIcon/></a> ( z : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>值替换为z。</p>
<h3 id="sub-v-vector3-this" tabindex="-1"><a class="header-anchor" href="#sub-v-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.sub" target="_blank" rel="noopener noreferrer">sub<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>从该向量减去向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="subscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#subscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.subScalar" target="_blank" rel="noopener noreferrer">subScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>从该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.z" target="_blank" rel="noopener noreferrer">z<ExternalLinkIcon/></a>中减去标量s。</p>
<h3 id="subvectors-a-vector3-b-vector3-this" tabindex="-1"><a class="header-anchor" href="#subvectors-a-vector3-b-vector3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.subVectors" target="_blank" rel="noopener noreferrer">subVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">Vector3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector3" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - （可选）被用于存储向量的数组。如果这个值没有传入，则将创建一个新的数组。
offset - （可选） 数组中元素的偏移量。</p>
<p>返回一个数组[x, y ,z]，或者将x、y和z复制到所传入的array中。</p>
<h3 id="transformdirection-m-matrix4-this" tabindex="-1"><a class="header-anchor" href="#transformdirection-m-matrix4-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.transformDirection" target="_blank" rel="noopener noreferrer">transformDirection<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">Matrix4<ExternalLinkIcon/></a> ) : this</h3>
<p>通过传入的矩阵（<a href="https://threejs.org/docs/index.html#api/zh/math/Matrix4" target="_blank" rel="noopener noreferrer">m<ExternalLinkIcon/></a>的左上角3 x 3子矩阵）变换向量的方向， 并将结果进行<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.normalize" target="_blank" rel="noopener noreferrer">normalizes<ExternalLinkIcon/></a>（归一化）。</p>
<h3 id="unproject-camera-camera-this" tabindex="-1"><a class="header-anchor" href="#unproject-camera-camera-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.unproject" target="_blank" rel="noopener noreferrer">unproject<ExternalLinkIcon/></a> ( camera : <a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera" target="_blank" rel="noopener noreferrer">Camera<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/cameras/Camera" target="_blank" rel="noopener noreferrer">camera<ExternalLinkIcon/></a> — 在投影中使用的摄像机。</p>
<p>将此向量(坐标)从相机的标准化设备坐标 (NDC) 空间投影到世界空间。</p>
<h3 id="random-this" tabindex="-1"><a class="header-anchor" href="#random-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector3.random" target="_blank" rel="noopener noreferrer">random<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量的每个分量(x、y、z)设置为介于 0 和 1 之间的伪随机数，不包括 1。</p>
</div></template>


