<template><div><h1 id="二维向量-vector2" tabindex="-1"><a class="header-anchor" href="#二维向量-vector2" aria-hidden="true">#</a> 二维向量（Vector2）</h1>
<p>表示2D <a href="https://en.wikipedia.org/wiki/Vector_space" target="_blank" rel="noopener noreferrer">vector<ExternalLinkIcon/></a>（二维向量）的类。 一个二维向量是一对有顺序的数字（标记为x和y），可用来表示很多事物，例如：</p>
<ul>
<li>一个位于二维空间中的点（例如一个在平面上的点）。</li>
<li>一个在平面上的方向与长度的定义。在three.js中，长度总是从(0, 0)到(x, y)的 <a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean distance<ExternalLinkIcon/></a>（欧几里德距离，即直线距离）， 方向也是从(0, 0)到(x, y)的方向。</li>
<li>任意的、有顺序的一对数字。</li>
</ul>
<p>其他的一些事物也可以使用二维向量进行表示，比如说动量矢量、复数等等；但以上这些是它在three.js中的常用用途。</p>
<p>对 Vector2 实例进行遍历将按相应的顺序生成它的分量 (x, y)。</p>
<h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例" aria-hidden="true">#</a> 代码示例</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> a <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">THREE<span class="token punctuation">.</span>Vector2</span><span class="token punctuation">(</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//no arguments; will be initialised to (0, 0) const b = new THREE.Vector2( ); const d = a.distanceTo( b );</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="构造函数" tabindex="-1"><a class="header-anchor" href="#构造函数" aria-hidden="true">#</a> 构造函数</h2>
<h3 id="vector2-x-float-y-float" tabindex="-1"><a class="header-anchor" href="#vector2-x-float-y-float" aria-hidden="true">#</a> Vector2( x : Float, y : Float )</h3>
<p>x - 向量的x值，默认为<strong>0</strong>。
y - 向量的y值，默认为<strong>0</strong>。</p>
<p>创建一个新的Vector2。</p>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<h3 id="height-float" tabindex="-1"><a class="header-anchor" href="#height-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.height" target="_blank" rel="noopener noreferrer">height<ExternalLinkIcon/></a> : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>的别名。</p>
<h3 id="isvector2-boolean" tabindex="-1"><a class="header-anchor" href="#isvector2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.isVector2" target="_blank" rel="noopener noreferrer">isVector2<ExternalLinkIcon/></a> : Boolean</h3>
<p>Read-only flag to check if a given object is of type Vector2.</p>
<h3 id="width-float" tabindex="-1"><a class="header-anchor" href="#width-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.width" target="_blank" rel="noopener noreferrer">width<ExternalLinkIcon/></a> : Float</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>的别名。</p>
<h3 id="x-float" tabindex="-1"><a class="header-anchor" href="#x-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a> : Float</h3>
<h3 id="y-float" tabindex="-1"><a class="header-anchor" href="#y-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a> : Float</h3>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<h3 id="add-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#add-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.add" target="_blank" rel="noopener noreferrer">add<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>和这个向量相加。</p>
<h3 id="addscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.addScalar" target="_blank" rel="noopener noreferrer">addScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将传入的标量s和这个向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值相加。</p>
<h3 id="addscaledvector-v-vector2-s-float-this" tabindex="-1"><a class="header-anchor" href="#addscaledvector-v-vector2-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.addScaledVector" target="_blank" rel="noopener noreferrer">addScaledVector<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, s : Float ) : this</h3>
<p>将所传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>与s相乘所得乘积和这个向量相加。</p>
<h3 id="addvectors-a-vector2-b-vector2-this" tabindex="-1"><a class="header-anchor" href="#addvectors-a-vector2-b-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.addVectors" target="_blank" rel="noopener noreferrer">addVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为 <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> + <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="angle-float" tabindex="-1"><a class="header-anchor" href="#angle-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.angle" target="_blank" rel="noopener noreferrer">angle<ExternalLinkIcon/></a> () : Float</h3>
<p>计算该向量相对于x轴正方向的弧度角度。</p>
<h3 id="applymatrix3-m-matrix3-this" tabindex="-1"><a class="header-anchor" href="#applymatrix3-m-matrix3-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.applyMatrix3" target="_blank" rel="noopener noreferrer">applyMatrix3<ExternalLinkIcon/></a> ( m : <a href="https://threejs.org/docs/index.html#api/zh/math/Matrix3" target="_blank" rel="noopener noreferrer">Matrix3<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量乘以三阶矩阵m（第三个值隐式地为1）。</p>
<h3 id="ceil-this" tabindex="-1"><a class="header-anchor" href="#ceil-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.ceil" target="_blank" rel="noopener noreferrer">ceil<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>分量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量向上取整为最接近的整数值。</p>
<h3 id="clamp-min-vector2-max-vector2-this" tabindex="-1"><a class="header-anchor" href="#clamp-min-vector2-max-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.clamp" target="_blank" rel="noopener noreferrer">clamp<ExternalLinkIcon/></a> ( min : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, max : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> - 在限制范围内，x和y的最小值。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> - 在限制范围内，x和y的最大值。</p>
<p>如果该向量的x值或y值大于限制范围内最大x值或y值，则该值将会被所对应的值取代。</p>
<p>如果该向量的x值或y值小于限制范围内最小x值或y值，则该值将会被所对应的值取代。</p>
<h3 id="clamplength-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clamplength-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.clampLength" target="_blank" rel="noopener noreferrer">clampLength<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 长度将被限制为的最小值
max - 长度将被限制为的最大值</p>
<p>如果向量长度大于最大值，则它将会被最大值所取代。</p>
<p>如果向量长度小于最小值，则它将会被最小值所取代。</p>
<h3 id="clampscalar-min-float-max-float-this" tabindex="-1"><a class="header-anchor" href="#clampscalar-min-float-max-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.clampScalar" target="_blank" rel="noopener noreferrer">clampScalar<ExternalLinkIcon/></a> ( min : Float, max : Float ) : this</h3>
<p>min - 分量将被限制为的最小值
max - 分量将被限制为的最大值</p>
<p>如果该向量的x值或y值大于最大值，则它们将被最大值所取代。</p>
<p>如果该向量的x值或y值小于最小值，则它们将被最小值所取代。</p>
<h3 id="clone-vector2" tabindex="-1"><a class="header-anchor" href="#clone-vector2" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.clone" target="_blank" rel="noopener noreferrer">clone<ExternalLinkIcon/></a> () : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a></h3>
<p>返回一个新的Vector2，其具有和当前这个向量相同的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>。</p>
<h3 id="copy-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#copy-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.copy" target="_blank" rel="noopener noreferrer">copy<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将所传入Vector2的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>属性复制给这一Vector2。</p>
<h3 id="distanceto-v-vector2-float" tabindex="-1"><a class="header-anchor" href="#distanceto-v-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.distanceTo" target="_blank" rel="noopener noreferrer">distanceTo<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector到传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的距离。</p>
<h3 id="manhattandistanceto-v-vector2-float" tabindex="-1"><a class="header-anchor" href="#manhattandistanceto-v-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.manhattanDistanceTo" target="_blank" rel="noopener noreferrer">manhattanDistanceTo<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector到传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的曼哈顿距离（<a href="https://en.wikipedia.org/wiki/Taxicab_geometry" target="_blank" rel="noopener noreferrer">Manhattan distance<ExternalLinkIcon/></a>）。</p>
<h3 id="distancetosquared-v-vector2-float" tabindex="-1"><a class="header-anchor" href="#distancetosquared-v-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.distanceToSquared" target="_blank" rel="noopener noreferrer">distanceToSquared<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该向量到传入的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的平方距离。 如果你只是将该距离和另一个距离进行比较，则应当比较的是距离的平方， 因为它的计算效率会更高一些。</p>
<h3 id="divide-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#divide-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.divide" target="_blank" rel="noopener noreferrer">divide<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量除以向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="dividescalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#dividescalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.divideScalar" target="_blank" rel="noopener noreferrer">divideScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量除以标量s。</p>
<h3 id="dot-v-vector2-float" tabindex="-1"><a class="header-anchor" href="#dot-v-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.dot" target="_blank" rel="noopener noreferrer">dot<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector和所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的点积（<a href="https://en.wikipedia.org/wiki/Dot_product" target="_blank" rel="noopener noreferrer">dot product<ExternalLinkIcon/></a>）。</p>
<h3 id="cross-v-vector2-float" tabindex="-1"><a class="header-anchor" href="#cross-v-vector2-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.cross" target="_blank" rel="noopener noreferrer">cross<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Float</h3>
<p>计算该vector和所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的叉积（<a href="https://en.wikipedia.org/wiki/Cross_product" target="_blank" rel="noopener noreferrer">cross product<ExternalLinkIcon/></a>）。 请注意，“叉积”在2D中并没有被明确定义。该函数计算的是2D图形中经常使用的几何叉积。</p>
<h3 id="equals-v-vector2-boolean" tabindex="-1"><a class="header-anchor" href="#equals-v-vector2-boolean" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.equals" target="_blank" rel="noopener noreferrer">equals<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : Boolean</h3>
<p>检查该向量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的严格相等性。</p>
<h3 id="floor-this" tabindex="-1"><a class="header-anchor" href="#floor-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.floor" target="_blank" rel="noopener noreferrer">floor<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>分量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量向下取整为最接近的整数值。</p>
<h3 id="fromarray-array-array-offset-integer-this" tabindex="-1"><a class="header-anchor" href="#fromarray-array-array-offset-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.fromArray" target="_blank" rel="noopener noreferrer">fromArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : this</h3>
<p>array - 来源的数组。
offset - （可选）在数组中的元素偏移量，默认值为0。</p>
<p>设置向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值为array[ offset ]，<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值为array[ offset + 1 ]。</p>
<h3 id="frombufferattribute-attribute-bufferattribute-index-integer-this" tabindex="-1"><a class="header-anchor" href="#frombufferattribute-attribute-bufferattribute-index-integer-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.fromBufferAttribute" target="_blank" rel="noopener noreferrer">fromBufferAttribute<ExternalLinkIcon/></a> ( attribute : <a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">BufferAttribute<ExternalLinkIcon/></a>, index : Integer ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a> - 来源的attribute。
index - 在attribute中的索引。</p>
<p>从<a href="https://threejs.org/docs/index.html#api/zh/core/BufferAttribute" target="_blank" rel="noopener noreferrer">attribute<ExternalLinkIcon/></a>中设置向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值。 、</p>
<h3 id="getcomponent-index-integer-float" tabindex="-1"><a class="header-anchor" href="#getcomponent-index-integer-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.getComponent" target="_blank" rel="noopener noreferrer">getComponent<ExternalLinkIcon/></a> ( index : Integer ) : Float</h3>
<p>index - 0 或 1</p>
<p>如果index值为0则返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值。
如果index值为1则返回<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值。</p>
<h3 id="length-float" tabindex="-1"><a class="header-anchor" href="#length-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0)到(x, y)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）。</p>
<h3 id="manhattanlength-float" tabindex="-1"><a class="header-anchor" href="#manhattanlength-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.manhattanLength" target="_blank" rel="noopener noreferrer">manhattanLength<ExternalLinkIcon/></a> () : Float</h3>
<p>计算该向量的曼哈顿长度（<a href="http://en.wikipedia.org/wiki/Taxicab_geometry" target="_blank" rel="noopener noreferrer">Manhattan length<ExternalLinkIcon/></a>）。</p>
<h3 id="lengthsq-float" tabindex="-1"><a class="header-anchor" href="#lengthsq-float" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.lengthSq" target="_blank" rel="noopener noreferrer">lengthSq<ExternalLinkIcon/></a> () : Float</h3>
<p>计算从(0, 0)到(x, y)的欧几里得长度 （<a href="https://en.wikipedia.org/wiki/Euclidean_distance" target="_blank" rel="noopener noreferrer">Euclidean length<ExternalLinkIcon/></a>，即直线长度）的平方。 如果你正在比较向量的长度，应当比较的是长度的平方，因为它的计算效率更高一些。</p>
<h3 id="lerp-v-vector2-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerp-v-vector2-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.lerp" target="_blank" rel="noopener noreferrer">lerp<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围通常在[0, 1]闭区间。</p>
<p>在该向量与传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>之间的线性插值，alpha是沿着线的长度的百分比 —— alpha = 0 时表示的是当前向量，alpha = 1 时表示的是所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="lerpvectors-v1-vector2-v2-vector2-alpha-float-this" tabindex="-1"><a class="header-anchor" href="#lerpvectors-v1-vector2-v2-vector2-alpha-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.lerpVectors" target="_blank" rel="noopener noreferrer">lerpVectors<ExternalLinkIcon/></a> ( v1 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, v2 : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, alpha : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a> - 起始的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>。
<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a> - 朝着进行插值的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>。
alpha - 插值因数，其范围通常在[0, 1]闭区间。</p>
<p>将此向量设置为在<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>之间进行线性插值的向量， 其中alpha为两个向量之间连线的长度的百分比 —— alpha = 0 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v1<ExternalLinkIcon/></a>，alpha = 1 时表示的是<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v2<ExternalLinkIcon/></a>。</p>
<h3 id="negate-this" tabindex="-1"><a class="header-anchor" href="#negate-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.negate" target="_blank" rel="noopener noreferrer">negate<ExternalLinkIcon/></a> () : this</h3>
<p>向量取反，即： x = -x , y = -y。</p>
<h3 id="normalize-this" tabindex="-1"><a class="header-anchor" href="#normalize-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.normalize" target="_blank" rel="noopener noreferrer">normalize<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量转换为单位向量（<a href="https://en.wikipedia.org/wiki/Unit_vector" target="_blank" rel="noopener noreferrer">unit vector<ExternalLinkIcon/></a>）， 也就是说，将该向量的方向设置为和原向量相同，但是其长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为1。</p>
<h3 id="max-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#max-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.max" target="_blank" rel="noopener noreferrer">max<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值或y值小于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值或y值，则将该值替换为对应的最大值。</p>
<h3 id="min-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#min-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.min" target="_blank" rel="noopener noreferrer">min<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>如果该向量的x值或y值大于所传入<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>的x值或y值，则将该值替换为对应的最小值。</p>
<h3 id="multiply-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#multiply-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.multiply" target="_blank" rel="noopener noreferrer">multiply<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量与所传入的向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>进行相乘。</p>
<h3 id="multiplyscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#multiplyscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.multiplyScalar" target="_blank" rel="noopener noreferrer">multiplyScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>将该向量与所传入的标量s进行相乘。</p>
<h3 id="rotatearound-center-vector2-angle-float-this" tabindex="-1"><a class="header-anchor" href="#rotatearound-center-vector2-angle-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.rotateAround" target="_blank" rel="noopener noreferrer">rotateAround<ExternalLinkIcon/></a> ( center : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, angle : Float ) : this</h3>
<p><a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a> - 将被围绕旋转的点。
angle - 将要旋转的角度，以弧度来表示。</p>
<p>将向量围绕着<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">center<ExternalLinkIcon/></a>旋转angle弧度。</p>
<h3 id="round-this" tabindex="-1"><a class="header-anchor" href="#round-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.round" target="_blank" rel="noopener noreferrer">round<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>分量和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量四舍五入取整为最接近的整数值。</p>
<h3 id="roundtozero-this" tabindex="-1"><a class="header-anchor" href="#roundtozero-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.roundToZero" target="_blank" rel="noopener noreferrer">roundToZero<ExternalLinkIcon/></a> () : this</h3>
<p>向量中的分量朝向0取整数（若分量为负数则向上取整，若为正数则向下取整）。</p>
<h3 id="set-x-float-y-float-this" tabindex="-1"><a class="header-anchor" href="#set-x-float-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.set" target="_blank" rel="noopener noreferrer">set<ExternalLinkIcon/></a> ( x : Float, y : Float ) : this</h3>
<p>设置该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>分量。</p>
<h3 id="setcomponent-index-integer-value-float-this" tabindex="-1"><a class="header-anchor" href="#setcomponent-index-integer-value-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.setComponent" target="_blank" rel="noopener noreferrer">setComponent<ExternalLinkIcon/></a> ( index : Integer, value : Float ) : this</h3>
<p>index - 0 或 1
value - Float</p>
<p>如果index值为0则将<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值设置为value。
如果index值为1则将<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值设置为value</p>
<h3 id="setlength-l-float-this" tabindex="-1"><a class="header-anchor" href="#setlength-l-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.setLength" target="_blank" rel="noopener noreferrer">setLength<ExternalLinkIcon/></a> ( l : Float ) : this</h3>
<p>将该向量的方向设置为和原向量相同，但是长度（<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.length" target="_blank" rel="noopener noreferrer">length<ExternalLinkIcon/></a>）为l。</p>
<h3 id="setscalar-scalar-float-this" tabindex="-1"><a class="header-anchor" href="#setscalar-scalar-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.setScalar" target="_blank" rel="noopener noreferrer">setScalar<ExternalLinkIcon/></a> ( scalar : Float ) : this</h3>
<p>将该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>、<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值同时设置为等于传入的scalar。</p>
<h3 id="setx-x-float-this" tabindex="-1"><a class="header-anchor" href="#setx-x-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.setX" target="_blank" rel="noopener noreferrer">setX<ExternalLinkIcon/></a> ( x : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>值替换为x。</p>
<h3 id="sety-y-float-this" tabindex="-1"><a class="header-anchor" href="#sety-y-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.setY" target="_blank" rel="noopener noreferrer">setY<ExternalLinkIcon/></a> ( y : Float ) : this</h3>
<p>将向量中的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>值替换为y。</p>
<h3 id="sub-v-vector2-this" tabindex="-1"><a class="header-anchor" href="#sub-v-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.sub" target="_blank" rel="noopener noreferrer">sub<ExternalLinkIcon/></a> ( v : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>从该向量减去向量<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">v<ExternalLinkIcon/></a>。</p>
<h3 id="subscalar-s-float-this" tabindex="-1"><a class="header-anchor" href="#subscalar-s-float-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.subScalar" target="_blank" rel="noopener noreferrer">subScalar<ExternalLinkIcon/></a> ( s : Float ) : this</h3>
<p>从该向量的<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.x" target="_blank" rel="noopener noreferrer">x<ExternalLinkIcon/></a>和<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.y" target="_blank" rel="noopener noreferrer">y<ExternalLinkIcon/></a>中减去标量s。</p>
<h3 id="subvectors-a-vector2-b-vector2-this" tabindex="-1"><a class="header-anchor" href="#subvectors-a-vector2-b-vector2-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.subVectors" target="_blank" rel="noopener noreferrer">subVectors<ExternalLinkIcon/></a> ( a : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a>, b : <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">Vector2<ExternalLinkIcon/></a> ) : this</h3>
<p>将该向量设置为<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">a<ExternalLinkIcon/></a> - <a href="https://threejs.org/docs/index.html#api/zh/math/Vector2" target="_blank" rel="noopener noreferrer">b<ExternalLinkIcon/></a>。</p>
<h3 id="toarray-array-array-offset-integer-array" tabindex="-1"><a class="header-anchor" href="#toarray-array-array-offset-integer-array" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.toArray" target="_blank" rel="noopener noreferrer">toArray<ExternalLinkIcon/></a> ( array : Array, offset : Integer ) : Array</h3>
<p>array - （可选）被用于存储向量的数组。如果这个值没有传入，则将创建一个新的数组。
offset - （可选） 数组中元素的偏移量。</p>
<p>返回一个数组[x, y]，或者将x和y复制到所传入的array中。</p>
<h3 id="random-this" tabindex="-1"><a class="header-anchor" href="#random-this" aria-hidden="true">#</a> .<a href="https://threejs.org/docs/index.html#api/zh/math/Vector2.random" target="_blank" rel="noopener noreferrer">random<ExternalLinkIcon/></a> () : this</h3>
<p>将该向量的每个分量(x、y)设置为介于 0 和 1 之间的伪随机数，不包括 1。</p>
</div></template>


